## 작업위치 확인 및 변경
- 파일 불러오기 전 작업

In [ ]:
# 구글 드라이브 연결하기
from google.colab import drive
drive.mount('/content/drive')

# 현재 작업 위치 확인하기
import os
print(os.getcwd())

# 작업위치 변경하기
%cd /content/drive/MyDrive/Colab Notebooks/실전프로젝트

# data 폴더 내에 json 파일 확인하기
import glob
json_files = glob.glob("data/*.json")
print("================================= 불러올 파일 확인 ====================================")
print("JSON 파일 개수:", len(json_files))
print(json_files)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/Colab Notebooks/실전프로젝트
/content/drive/MyDrive/Colab Notebooks/실전프로젝트
================================= 불러올 파일 확인 ====================================
JSON 파일 개수: 12
['data/final_news_2023.json', 'data/final_news_2025.json', 'data/final_news_2024.json', 'data/final_news_2026.json', 'data/raw_news_2025_part1.json', 'data/raw_news_2026_part1.json', 'data/raw_news_2023_part1.json', 'data/raw_news_2024_part1.json', 'data/raw_news_2025_part2.json', 'data/raw_news_2024_part2.json', 'data/raw_news_2023_part2.json', 'data/raw_news_2026_part2.json']

## 전처리 방법 고민
- json 파일 불러와서 전처리 작업 진행
- ['data/final_news_2023.json', 'data/final_news_2025.json', 'data/final_news_2024.json', 'data/final_news_2026.json']

#### 파일 불러오기
- 내림차순 기준 20개 선택

In [ ]:
import json
import os
import pandas as pd

# 전처리에 사용 할 data/final_news_2023.json 데이터 불러오기
# 불러올 JSON 파일 1개만 지정
file_path = "data/raw_news_2023_part1.json"

# JSON 파일 불러오기
with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

print("파일 경로:", file_path)
print("데이터 타입:", type(data))

print("======================================================================")

# 데이터가 리스트 형태인 경우
if isinstance(data, list):
    print("전체 데이터 개수:", len(data))

    print("\n첫 번째 데이터 타입:", type(data[0]))
    print("\n첫 번째 데이터 내용:")
    print(json.dumps(data[0], ensure_ascii=False, indent=2))

    # 첫 번째 데이터가 딕셔너리라면 key 확인
    if isinstance(data[0], dict):
        print("\n첫 번째 데이터의 key 목록:")
        print(data[0].keys())
print("==============================  데이터 결측치 확인 ==========================")

# JSON 데이터를 DataFrame으로 변환
df = pd.DataFrame(data)

# 전체 데이터 크기 확인
print("데이터 크기:", df.shape)

# 컬럼별 결측치 개수 확인
print("\n컬럼별 결측치 개수:")
print(df.isnull().sum())

print("==============================  20개 샘플 데이터 복사본 생성 ==========================")

# 전체 df에서 앞의 20개 데이터만 선택하여 복사본 생성
# 원본 df는 그대로 유지하고, 이후 전처리 작업은 df_20으로 진행
df_20 = df.head(20).copy()

# 20개만 잘 가져왔는지 확인
print("원본 데이터 크기:", df.shape)
print("20개 샘플 데이터 크기:", df_20.shape)

# 20개 샘플 데이터 일부 확인
df_20.head()

파일 경로: data/raw_news_2023_part1.json
데이터 타입: <class 'list'>
======================================================================
전체 데이터 개수: 955

첫 번째 데이터 타입: <class 'dict'>

첫 번째 데이터 내용:
{
  "source": "일반기사",
  "title": "“카카오 장애 소상공인 피해..지원금 지급 절차 시작”",
  "content": "전용 챗봇 등 모든 채널 열어 소상공인 피해 지원\n1월30일~2월27일 서류 접수..100명 규모 전담센터\n매출피해 입증 등 제출서류 검토 후 3월 지급 예정\n[파이낸셜뉴스] 카카오가 30일부터 오는 2월 27일까지 4주간 소상공인 피해 지원금 지급을 위한 서류 접수를 진행한다. 앞서 카카오 블랙아웃 사태와 관련, ‘1015 피해지원 협의체’에서 수립한 SK C&C 데이터센터 화재에 따른 서비스 장애 피해지원 원칙에 따른 후속조치다.\n카카오가 지난해 10월 15일 서비스 장애로 인해 피해를 입은 소상공인 대상으로 피해 지원금 지급 절차를 시작했다. 신청 화면 이미지. 카카오 제공\n이날 업계에 따르면 카카오는 지난해 10월19일부터 11월6일까지 공식 채널을 통해 신고했던 소상공인 대상으로 서류 접수를 시작한다. 또 오는 2월13일부터 27일까지 2주간 추가 접수도 진행한다. 기존 접수자 대상으로는 e메일과 카카오톡 메시지를 통해 서류 접수 절차에 대한 안내가 이뤄졌으며, 추가 접수 기간과 방법은 소상공인연합회 홈페이지를 통해서도 알릴 예정이다.\n카카오는 1015 피해지원 협의체가 수립한 원칙에 따라 △매출 손실 규모액이 30만원 이하인 경우 3만원 △30만원 초과 50만원 이하인 경우 5만원을 지급하고 △50만원 초과 피해 사례에 대해서는 피해 입증 과정을 거쳐 추가 지원을 검토한다. 지원금은 제출서류를 검토한 뒤, 오는 3월에 지급 완료할 계획이다.\n카카오는 또 생업으로 바쁜 소상공인이 최대한 간편하게 서류를 접수할 수 있도록 ‘공식 챗봇(대화형 AI)’도 마련했다. 카카오톡 채널에서 공식 챗봇 ‘카카오 1015 소상공인 지원센터’를 검색해 추가한 뒤, 여기에 해당 서류를 캡쳐하거나 카메라로 촬영한 이미지를 첨부하면 된다. 카카오는 공식 챗봇으로 서류 접수 가이드 안내부터 접수까지 한 번에 할 수 있도록 한 것은 물론 고객센터 웹페이지, 전화, 우편 등 서류 접수를 위한 모든 창구를 운영할 방침이다. 이를 위해 상담 인력 100여 명을 충원해 전담 고객센터도 함께 운영한다.\n소상공인들은 △소상공인 확인서 △장애로 인한 매출 피해 입증 자료 △카카오 서비스 이용 사실 자료 △상호명 또는 사업장 대표자 명의의 은행계좌 사본 등 서류를 제출하면 된다.\n카카오 측은 “법적으로 요구되는 불가피한 사항으로 서류 제출 절차는 거치지만, 피해 유형 중 대다수를 차지하는 카카오톡 메시지, 카카오톡 채널 장애의 경우 간략한 서비스 이용화면 캡쳐로 확인이 가능하도록 증빙 절차를 간소화했다”고 설명했다.\n카카오는 카카오 플랫폼을 활용해 영업을 하는 소상공인들을 지원하기 위해 2월 중에 카카오톡 채널 메시지를 2000여건 발송할 수 있는 5만원 상당 무상캐시 지급 프로그램도 진행한다.\n협의체 위원으로 참여한 카카오 송지혜 카카오톡 부문장은 “서비스 장애로 비즈니스 활동에 불편과 피해를 끼친 부분에 대해 다시 한 번 사과드린다”며 “소상공인과 상생 협력 및 사회적 책임을 다하기 위해 피해 지원금 지급 마무리까지 최선의 노력을 다할 것”이라고 강조했다.\n한편 카카오는 지난해 12월29일 1015 피해지원 협의체에서 만든 서비스 장애 피해지원 방안을 발표했다. 협의체는 카카오 서비스를 이용하는 국내 일반 이용자와 장애로 영업에 피해를 입은 비즈니스 파트너로 구분해 진행하기로 결정했다. 이에 따라 지난 1월 5일부터 20일까지 전 국민 대상으로 장애 원인과 재발 방지 대책을 담은 다짐보고서와 이모티콘 3종 등을 지급했다.\n#소상공인 #카카오 #챗봇 #데이터센터 #블랙아웃",
  "url": "https://n.news.naver.com/mnews/article/014/0004961753?sid=105",
  "published_at": "2023-01-30 15:37:01",
  "collected_at": "2026-05-26 10:46:28",
  "status": "수집",
  "category": "소상공인",
  "summary": "전용 챗봇 등 모든 채널 열어 소상공인 피해 지원\n1월30일~2월27일 서류 접수..100명 규모 전담센터\n매출피해 입증 등 제출서류 검토 후 3월 지급 예정\n[파이낸셜뉴스] 카카오가 30일부터 오는 2월 27일까지 4주간 소상공인 피해 지원금 지급을 위한 서류 접수를 진행한다. 앞서 카카오 블랙아웃 사태와 관련, ‘1015 피해지원 협의체’에서 수립한 SK C&C 데이터센터 화재에 따른 서비스 장애 피해지원 원칙에 따른 후속조치다.\n카카오가 지난해 10월 15일 서비스 장애로 인해 피해를 입은 소상공인 대상으로 피해 지원금 지급 ..."
}

첫 번째 데이터의 key 목록:
dict_keys(['source', 'title', 'content', 'url', 'published_at', 'collected_at', 'status', 'category', 'summary'])
==============================  데이터 결측치 확인 ==========================
데이터 크기: (955, 9)

컬럼별 결측치 개수:
source          0
title           0
content         0
url             0
published_at    0
collected_at    0
status          0
category        0
summary         0
dtype: int64
==============================  20개 샘플 데이터 복사본 생성 ==========================
원본 데이터 크기: (955, 9)
20개 샘플 데이터 크기: (20, 9)

,source,title,content,url,published_at,collected_at,status,category,summary
0,일반기사,“카카오 장애 소상공인 피해..지원금 지급 절차 시작”,전용 챗봇 등 모든 채널 열어 소상공인 피해 지원\n1월30일~2월27일 서류 접수...,https://n.news.naver.com/mnews/article/014/000...,2023-01-30 15:37:01,2026-05-26 10:46:28,수집,소상공인,전용 챗봇 등 모든 채널 열어 소상공인 피해 지원\n1월30일~2월27일 서류 접수...
1,일반기사,"카카오, 소상공인 보상 시작… “다음 달 27일까지 서류 접수”",카카오톡 서비스 장애 피해 소상공인을 위한 보상금 지급 절차. /카카오\n카카오가 ...,https://n.news.naver.com/mnews/article/366/000...,2023-01-30 16:12:01,2026-05-26 10:46:28,수집,소상공인,카카오톡 서비스 장애 피해 소상공인을 위한 보상금 지급 절차. /카카오\n카카오가 ...
2,일반기사,"카카오, 서비스 장애 소상공인 추가 피해 접수받는다",챗봇 비롯 웹페이지·전화 등 채널 창구 열어…내달 27일까지 접수\n카카오가 서비스...,https://n.news.naver.com/mnews/article/092/000...,2023-01-30 16:42:01,2026-05-26 10:46:28,수집,소상공인,챗봇 비롯 웹페이지·전화 등 채널 창구 열어…내달 27일까지 접수\n카카오가 서비스...
3,일반기사,"카카오, '먹통 사태' 소상공인 보상 시작","다음달 27일까지 서류 접수, 3월 내 지급 마칠 예정\n[이데일리 김국배 기자] ...",https://n.news.naver.com/mnews/article/018/000...,2023-01-30 19:40:01,2026-05-26 10:46:28,수집,소상공인,"다음달 27일까지 서류 접수, 3월 내 지급 마칠 예정\n[이데일리 김국배 기자] ..."
4,KBS 뉴스,"카카오, ‘서비스 먹통’피해 소상공인 서류 접수 시작",카카오는 지난해 10월 일어난 서비스 먹통과 관련해 피해를 본 소상공인에 대한 지원...,https://news.kbs.co.kr/news/view.do?ncd=759290...,2023-01-30 00:00:00,2026-05-26 10:46:28,수집,소상공인,카카오는 지난해 10월 일어난 서비스 먹통과 관련해 피해를 본 소상공인에 대한 지원...

In [ ]:
df["category"].unique()

array(['소상공인', '1인창업', '자영업', '창업지원', '소자본창업'], dtype=object)

#### 파일 불러오기
- 카테고리 컬럼 선택해서 특정 값 지정해 랜덤으로 20개

In [ ]:
import json
import os
import pandas as pd

# 전처리에 사용 할 데이터 불러오기
# 불러올 JSON 파일 1개만 지정
file_path = "data/raw_news_2023_part2.json"

# JSON 파일 불러오기
with open(file_path, "r", encoding="utf-8") as f:
    data = json.load(f)

print("파일 경로:", file_path)
print("데이터 타입:", type(data))

print("======================================================================")

# 데이터가 리스트 형태인 경우
if isinstance(data, list):
    print("전체 데이터 개수:", len(data))

    print("\n첫 번째 데이터 타입:", type(data[0]))
    print("\n첫 번째 데이터 내용:")
    print(json.dumps(data[0], ensure_ascii=False, indent=2))

    # 첫 번째 데이터가 딕셔너리라면 key 확인
    if isinstance(data[0], dict):
        print("\n첫 번째 데이터의 key 목록:")
        print(data[0].keys())

print("==============================  데이터 결측치 확인 ==========================")

# JSON 데이터를 DataFrame으로 변환
df = pd.DataFrame(data)

# 전체 데이터 크기 확인
print("데이터 크기:", df.shape)

# 컬럼별 결측치 개수 확인
print("\n컬럼별 결측치 개수:")
print(df.isnull().sum())

print("==============================  '창업트렌드' 카테고리 랜덤 20개 샘플 데이터 복사본 생성 ==========================")

# category 컬럼 값이 '1인창업'인 데이터만 필터링
df_one_person = df[df["category"] == "창업트렌드"].copy()

# '1인창업' 데이터 중 랜덤으로 100개 선택하여 복사본 생성
df_20 = df_one_person.sample(n=100, random_state=42).copy()

# 결과 확인
print("원본 데이터 크기:", df.shape)
print("'창업트렌드' 데이터 크기:", df_one_person.shape)
print("랜덤 20개 샘플 데이터 크기:", df_20.shape)

# 20개 샘플 데이터 일부 확인
df_20.head()

파일 경로: data/raw_news_2023_part2.json
데이터 타입: <class 'list'>
======================================================================
전체 데이터 개수: 957

첫 번째 데이터 타입: <class 'dict'>

첫 번째 데이터 내용:
{
  "source": "일반기사",
  "title": "카페24, 창업센터 입주자 대상 빅데이터 분석 서비스 제공",
  "content": "/카페24\n카페24는 창업센터 입주자를 위한 이커머스 데이터 분석 솔루션인 ‘아이템스카우트’ 서비스를 출시했다고 30일 밝혔다.\n카페24 창업센터를 이용하는 온라인 사업자는 회원가입 후 서비스를 무료로 이용할 수 있다.\n아이템스카우트는 온라인 판매 상품 정보와 검색량 등 데이터를 기반으로 소비자 행동을 분석해 준다. 온라인 사업자들은 기간별 키워드 순위, 키워드별 검색 수, 상품 수 등 데이터를 활용해 수익성 높은 판매 상품을 찾아 판매 전략을 세울 수 있다.\n박재만 카페24 창업센터 팀장은 “온라인 사업은 변화하는 시장 트렌드나 경쟁력 있는 상품을 찾아내 신속하게 대응하는 것이 중요하다”며 “창업센터에 입주한 사업자들이 데이터 분석 솔루션을 활용해 비즈니스를 성장해나갈 수 있도록 지원하겠다”고 말했다.",
  "url": "https://n.news.naver.com/mnews/article/366/0000873169?sid=101",
  "published_at": "2023-01-30 11:53:04",
  "collected_at": "2026-05-26 10:46:31",
  "status": "수집",
  "category": "창업트렌드",
  "summary": "/카페24\n카페24는 창업센터 입주자를 위한 이커머스 데이터 분석 솔루션인 ‘아이템스카우트’ 서비스를 출시했다고 30일 밝혔다.\n카페24 창업센터를 이용하는 온라인 사업자는 회원가입 후 서비스를 무료로 이용할 수 있다.\n아이템스카우트는 온라인 판매 상품 정보와 검색량 등 데이터를 기반으로 소비자 행동을 분석해 준다. 온라인 사업자들은 기간별 키워드 순위, 키워드별 검색 수, 상품 수 등 데이터를 활용해 수익성 높은 판매 상품을 찾아 판매 전략을 세울 수 있다.\n박재만 카페24 창업센터 팀장은 “온라인 사업은 변화하는 시장 트렌드나 ..."
}

첫 번째 데이터의 key 목록:
dict_keys(['source', 'title', 'content', 'url', 'published_at', 'collected_at', 'status', 'category', 'summary'])
==============================  데이터 결측치 확인 ==========================
데이터 크기: (957, 9)

컬럼별 결측치 개수:
source          0
title           0
content         0
url             0
published_at    0
collected_at    0
status          0
category        0
summary         0
dtype: int64
==============================  '창업트렌드' 카테고리 랜덤 20개 샘플 데이터 복사본 생성 ==========================
원본 데이터 크기: (957, 9)
'창업트렌드' 데이터 크기: (240, 9)
랜덤 20개 샘플 데이터 크기: (100, 9)

,source,title,content,url,published_at,collected_at,status,category,summary
24,이투데이,"LG전자, '금성사 창업 정신 계승' 사내벤처 프로그램 ‘스튜디오341’ 가...",금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명\n\n미래 산업 분야 사업 ...,https://www.etoday.co.kr/news/view/2253133,2023-05-30 00:00:00,2026-05-26 10:47:22,수집,창업트렌드,금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명\n\n미래 산업 분야 사업 ...
6,식품저널 foodnews,"프랜차이즈산업협회, 올해 4회 창업 박람회 연다",‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,http://www.foodnews.co.kr/news/articleView.htm...,2023-02-28 00:00:00,2026-05-26 10:46:53,수집,창업트렌드,‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...
333,스트레이트뉴스,"농협카드, 소상공인·예비창업자에 데이터 제공",NH농협카드 CI\n\nNH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 ...,https://www.straightnews.co.kr/news/articleVie...,2023-07-30 00:00:00,2026-05-26 11:51:58,수집,창업트렌드,NH농협카드 CI\n\nNH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 ...
349,연합뉴스,판교서 '스타트업 위크' 개막…창업·기술·투자의 만남,김경태기자 구독 구독중 이전 다음\n\n(수원=연합뉴스) 김경태 기자 = 30일 성...,https://www.yna.co.kr/view/AKR2023103013510006...,2023-10-30 00:00:00,2026-05-26 11:52:28,수집,창업트렌드,경기도경제과학진흥원이 '스타트업 판교에서 유니콘으로'를 주제로 주최한 이번 행사는 ...
344,메트로신문,"부산보건대, 혁신지원사업 프로그램 창업캠프 성료",사진/부산보건대학교\n\n부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로...,http://www.metroseoul.co.kr/article/2023092650...,2023-09-26 00:00:00,2026-05-26 11:52:18,수집,창업트렌드,사진/부산보건대학교\n\n부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로...

#### 뉴스 본문 텍스트 노이즈 제거 코드
- clean_content : 노이즈 제거된 문장 데이터 (BERTopic 입력용)

In [ ]:
import re
import pandas as pd


def clean_content(text):
    # content 값이 비어 있거나 NaN인 경우 빈 문자열로 처리
    if pd.isna(text):
        return ""

    # 숫자, NaN 등이 섞여 있을 가능성을 대비해 문자열로 변환
    text = str(text)

    # 이메일 주소 제거
    # 예: abc@gmail.com, reporter@news.co.kr
    text = re.sub(
        r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",
        " ",
        text
    )

    # URL 제거
    # 예: http://example.com, https://news.com/article
    text = re.sub(
        r"http[s]?://\S+|www\.\S+",
        " ",
        text
    )

    # 실제 줄바꿈, 엔터, 탭 문자 제거
    # 예: \n, \r, \t
    text = re.sub(r"[\n\r\t]", " ", text)

    # 문자열 형태로 저장된 줄바꿈 문자 제거
    # 예: "\\n" 형태로 들어간 문자
    text = text.replace("\\n", " ")

    # 이스케이프된 따옴표 제거
    # 예: \'벤처·스타트업 근로시간 제도개편 간담회\'
    # 결과: 벤처·스타트업 근로시간 제도개편 간담회
    text = re.sub(r"\\['\"]", " ", text)

    # 본문에 남아 있는 \ 기호 제거
    # 예: \, \\, \\\ 등 연속된 \ 기호를 공백으로 변경
    text = re.sub(r"\\+", " ", text)

    # 일반 따옴표 제거
    # 예: '문장', "문장" 형태에서 따옴표만 제거
    text = re.sub(r"[\"']", " ", text)

    # <내용> 형태 제거
    # 예: <저작권자>, <사진>, <뉴스본문> 등 꺾쇠괄호와 내부 내용 전체 제거
    text = re.sub(r"<[^>]*>", " ", text)

    # 재판매 및 DB 금지 문구 제거
    # 예: *재판매 및 DB 금지, 재판매 및 DB 금지
    text = re.sub(
        r"\*?\s*재판매\s*및\s*DB\s*금지",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 대괄호로 묶인 출처/지역/언론사/광고 정보 제거
    # 예: [서울=뉴시스], [사진=대통령실 제공], [광고]
    # 대괄호와 그 안의 내용 전체를 제거함
    text = re.sub(r"\[[^\]]*\]", " ", text)

    # 소괄호로 묶인 사진 설명, 출처, 부가 설명 제거
    # 예: (사진=대통령실 제공), (대통령실통신사진기자단)
    # 소괄호와 그 안의 내용 전체를 제거함
    text = re.sub(r"\([^)]*\)", " ", text)

    # 기사 본문에 포함된 날짜 형식 제거
    # 예: 2023.01.31. / 2023.1.31
    text = re.sub(r"\d{4}\.\d{1,2}\.\d{1,2}\.?", " ", text)

    # 한글 이름 + 기자 표현 제거
    # 예: 홍길동 기자, 김철수기자
    text = re.sub(r"[가-힣]{2,4}\s*기자", " ", text)

    # 기자 = 형태 제거
    # 예: 기자=, 기자 =
    text = re.sub(r"기자\s*=", " ", text)

    # 저작권, 무단전재, 재배포 금지, 제보 문구 제거
    # 예: 무단 전재, 재배포 금지, Copyright, ⓒ, 제보를 기다립니다
    text = re.sub(
        r"(무단\s*전재|재배포\s*금지|ⓒ|Copyright|제보를 기다립니다)",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 불필요한 특수기호 제거
    # 예: ▲, ▶, *, =, … 기호 제거
    text = re.sub(r"[▲▶△*=…]", " ", text)

    # 여러 개의 공백을 하나의 공백으로 정리
    # 앞뒤 공백은 strip()으로 제거
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# content 컬럼의 원본 뉴스 본문을 전처리한 뒤 clean_content 컬럼에 저장
df_20["clean_content"] = df_20["content"].apply(clean_content)

# 전처리 전 content와 전처리 후 clean_content를 비교 확인
df_20[["content", "clean_content"]].head()

df_20.head()

,source,title,content,url,published_at,collected_at,status,category,summary,clean_content
24,이투데이,"LG전자, '금성사 창업 정신 계승' 사내벤처 프로그램 ‘스튜디오341’ 가...",금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명\n\n미래 산업 분야 사업 ...,https://www.etoday.co.kr/news/view/2253133,2023-05-30 00:00:00,2026-05-26 10:47:22,수집,창업트렌드,금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명\n\n미래 산업 분야 사업 ...,금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명 미래 산업 분야 사업 아이디...
6,식품저널 foodnews,"프랜차이즈산업협회, 올해 4회 창업 박람회 연다",‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,http://www.foodnews.co.kr/news/articleView.htm...,2023-02-28 00:00:00,2026-05-26 10:46:53,수집,창업트렌드,‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...
333,스트레이트뉴스,"농협카드, 소상공인·예비창업자에 데이터 제공",NH농협카드 CI\n\nNH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 ...,https://www.straightnews.co.kr/news/articleVie...,2023-07-30 00:00:00,2026-05-26 11:51:58,수집,창업트렌드,NH농협카드 CI\n\nNH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 ...,NH농협카드 CI NH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 편의성...
349,연합뉴스,판교서 '스타트업 위크' 개막…창업·기술·투자의 만남,김경태기자 구독 구독중 이전 다음\n\n(수원=연합뉴스) 김경태 기자 = 30일 성...,https://www.yna.co.kr/view/AKR2023103013510006...,2023-10-30 00:00:00,2026-05-26 11:52:28,수집,창업트렌드,경기도경제과학진흥원이 '스타트업 판교에서 유니콘으로'를 주제로 주최한 이번 행사는 ...,구독 구독중 이전 다음 30일 성남시 분당구 판교 스타트업캠퍼스에서 2023 경기 ...
344,메트로신문,"부산보건대, 혁신지원사업 프로그램 창업캠프 성료",사진/부산보건대학교\n\n부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로...,http://www.metroseoul.co.kr/article/2023092650...,2023-09-26 00:00:00,2026-05-26 11:52:18,수집,창업트렌드,사진/부산보건대학교\n\n부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로...,사진/부산보건대학교 부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로그램으...

In [ ]:
df_20["clean_content"][79]

'39세 이하 1인 무주택 청년창업인 대상 5월 4일까지 접수 서울 관악구는 청년 창업인에게 안정적인 주거·사무 공간을 제공해 자립을 돕는 청년맞춤형 공공임대 주택 ‘도전숙’ 에 입주할 청년 창업인 20명을 모집한다고 25일 밝혔다. 구는 대학동에 도전숙 20가구를 민간 임대주택보다 저렴한 임대료로 공급한다. 도전숙 입주 대상은 19세 이상 39세 이하의 관악구민 또는 관악구에 사업장을 둔 서울시민이다. 월평균 소득이 전년도 도시근로자 월평균 소득의 70% 이하여야 한다. 신청 기간은 5월 4일까지다. 관악구청 홈페이지 뉴스소식에 게시된 공고문을 참조해 관악구청 일자리벤처과로 이메일로 접수하면 된다. 구는 신청자를 대상으로 소득과 자산, 무주택 여부 등을 검증한 후 7월 24일 당첨자를 발표할 예정이다. 당첨자는 서울주택도시공사 와 임대차 계약을 체결한 후 8∼10월 중 입주할 수 있다.'

#### 노이즈 데이터 제거 후 불용어 사전 적용
- analysis_content: 명사추출 + 불용어 제거된 단어 데이터 (빈도 분석, 워드클라우드, 키워드 후보 확인용)

In [ ]:

!pip install kiwipiepy -q
from kiwipiepy import Kiwi
import pandas as pd

# 형태소 분석기 초기화
kiwi = Kiwi()


# ============================================================
# 불용어 사전
# ============================================================
# 분석에는 자주 등장하지만 의미가 약한 단어를 제거하기 위한 목록
# 프로젝트 결과를 확인하면서 계속 추가/수정하면 됨
# ============================================================

STOPWORDS = {
    # ============================================================
    # 1. 일반 불용어
    # ============================================================
    # 문장에 자주 등장하지만 키워드 분석 의미가 약한 단어
    "것", "수", "등", "및", "때", "중", "더", "또",
    "관련", "경우", "대상", "약",

    # ============================================================
    # 2. 조사·연결·전환 표현
    # ============================================================
    # 문장 연결에는 사용되지만 핵심 키워드로 보기 어려운 표현
    "위해", "통해", "대한", "또한", "한편",
    "따라", "이에", "다만", "특히",

    # ============================================================
    # 3. 시점 표현
    # ============================================================
    # 기사 작성 시점이나 시간 흐름을 나타내지만 트렌드 키워드로 보기 어려운 표현
    "이번", "지난", "올해", "내년", "최근", "현재", "향후",
    "오늘", "내일", "이날",

    # ============================================================
    # 4. 인물명 및 직책 관련 단어
    # ============================================================
    # 특정 인물명이나 직책명이 반복 등장하여
    # 창업 트렌드 키워드 분석에 불필요한 영향을 주는 경우 제거
    "윤석열", "모하메드",
    "대통령", "장관", "기자", "대표", "위원장",
    "의원", "총리", "회장", "사장", "교수",

    # ============================================================
    # 5. 지명 및 국가명
    # ============================================================
    # 특정 국가명·지역명이 반복적으로 등장하지만
    # 분석 목적상 핵심 키워드가 아닌 경우 제거
    "한국", "미국", "중국", "일본", "서울",
    "아랍에미리트", "부산", "인천", "경기",

    # ============================================================
    # 6. 기관명 및 기업명
    # ============================================================
    # 특정 기관명이나 기업명이 반복 등장하여
    # 전체 토픽/키워드 결과를 왜곡하는 경우 제거
    "중소벤처기업부", "중기부", "한국무역협회",
    "대한상공회의소", "벤처기업협회", "고용노동부",
    "두산에너빌리티",

    # ============================================================
    # 7. 언론사 및 뉴스 출처 관련 단어
    # ============================================================
    # 기사 출처나 언론사명으로, 트렌드 분석 키워드와 직접 관련이 낮은 단어
    "한국경제", "이투데이", "머니투데이",
    "뉴시스", "연합뉴스", "조선일보",

    # ============================================================
    # 8. 뉴스 기사 형식 관련 단어
    # ============================================================
    # 뉴스 본문 구조상 반복적으로 등장하는 표현
    "뉴스", "보도", "사진", "제공", "자료", "출처",
    "취재", "인터뷰", "관계자", "업계",

    # ============================================================
    # 9. 기사 서술 표현
    # ============================================================
    # 기사 문체에서 자주 등장하지만 핵심 키워드로 보기 어려운 표현
    "밝혔다", "말했다", "설명했다", "전했다", "덧붙였다",
    "설명", "강조", "진행", "개최", "발표", "참석",
    "예정", "참여",

    # ============================================================
    # 10. 분석 결과에서 의미가 약한 단어
    # ============================================================
    # 실제 키워드 추출 결과를 확인하며 추가한 프로젝트 맞춤형 불용어
    "광범위", "천문학"
}


# ============================================================
# 명사 추출 + 불용어 제거 함수
# ============================================================
# clean_content 컬럼의 문장 데이터에서 명사 중심 단어만 추출하고,
# 불용어 사전에 포함된 단어를 제거하여 분석용 텍스트를 생성한다.
# ============================================================

def remove_stopwords_and_extract_nouns(text):
    # 값이 비어 있거나 NaN인 경우 빈 문자열 반환
    if pd.isna(text):
        return ""

    text = str(text)

    words = []

    # Kiwi 형태소 분석 수행
    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사
        # NNP: 고유명사
        # SL: 영어/외국어 표현, 예: AI, ICT, ESG
        if pos in ["NNG", "NNP", "SL"]:

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            words.append(word)

    return " ".join(words)


# clean_content 컬럼을 기준으로 명사 추출 및 불용어 제거
df_20["analysis_content"] = df_20["clean_content"].apply(remove_stopwords_and_extract_nouns)

# 결과 확인
df_20[["content", "clean_content", "analysis_content"]].head()

,content,clean_content,analysis_content
24,금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명\n\n미래 산업 분야 사업 ...,금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명 미래 산업 분야 사업 아이디...,금성사 설립 연지동 번지 명명 미래 산업 분야 사업 아이디어 국내 임직원 선발 스타...
6,‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,IFS 프랜차이즈 창업 박람회 지난해 코엑스 프랜차이즈 산업 협회 중앙회 지회 전국...
333,NH농협카드 CI\n\nNH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 ...,NH농협카드 CI NH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 편의성...,NH농협카드 CI NH농협카드 학생 상공인 예비 창업자 고객 데이터 활용 편의 금융...
349,김경태기자 구독 구독중 이전 다음\n\n(수원=연합뉴스) 김경태 기자 = 30일 성...,구독 구독중 이전 다음 30일 성남시 분당구 판교 스타트업캠퍼스에서 2023 경기 ...,구독 구독 이전 다음 성남시 분당구 판교 스타트업 캠퍼스 스타트업 위크 이미지 확대...
344,사진/부산보건대학교\n\n부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로...,사진/부산보건대학교 부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로그램으...,부산보건대학교 부산보건대학교 이틀간 혁신 지원 사업 프로그램 창업 캠프 창업 캠프 ...

#### KeyBERT 작업 수행
- analysis_content 컬럼 사용

In [ ]:
!pip install keybert sentence-transformers -q
from keybert import KeyBERT
import pandas as pd


# ============================================================
# KeyBERT 키워드 추출
# ============================================================
# 사용 컬럼:
# - analysis_content
#   → 노이즈 제거 + 명사 추출 + 불용어 제거가 완료된 분석용 텍스트
#
# 결과 컬럼:
# - keybert_keywords
#   → 기사별 추출 키워드 목록
# - keybert_keyword_scores
#   → 기사별 키워드와 점수 정보
# ============================================================


# KeyBERT 모델 초기화
# 한국어 뉴스 데이터에도 사용할 수 있는 다국어 문장 임베딩 모델 사용
kw_model = KeyBERT(model="paraphrase-multilingual-MiniLM-L12-v2")


def extract_keybert_keywords(text):
    # 값이 비어 있거나 NaN인 경우 빈 리스트 반환
    if pd.isna(text):
        return []

    text = str(text).strip()

    # 전처리 결과가 비어 있는 경우 빈 리스트 반환
    if text == "":
        return []

    # KeyBERT 키워드 추출
    keywords = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1, 1),  # 1단어 또는 2단어 조합 키워드 추출
        stop_words=None,               # 불용어는 이미 analysis_content에서 제거했으므로 None
        top_n=10                       # 기사 1개당 상위 10개 키워드 추출
    )

    return keywords


# analysis_content 컬럼을 기준으로 KeyBERT 키워드 추출
df_20["keybert_keyword_scores"] = df_20["analysis_content"].apply(extract_keybert_keywords)

# 키워드만 따로 리스트 형태로 저장
df_20["keybert_keywords"] = df_20["keybert_keyword_scores"].apply(
    lambda keywords: [keyword for keyword, score in keywords]
)

# 결과 확인
df_20[["content", "clean_content", "analysis_content", "keybert_keywords", "keybert_keyword_scores"]].head()

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,content,clean_content,analysis_content,keybert_keywords,keybert_keyword_scores
24,금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명\n\n미래 산업 분야 사업 ...,금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명 미래 산업 분야 사업 아이디...,금성사 설립 연지동 번지 명명 미래 산업 분야 사업 아이디어 국내 임직원 선발 스타...,"[스타트업, 벤처, 혁신, 스튜디오, 창업, 모집, 임직원, 로봇, 현업, 기업]","[(스타트업, 0.5764), (벤처, 0.5478), (혁신, 0.5211), (..."
6,‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,IFS 프랜차이즈 창업 박람회 지난해 코엑스 프랜차이즈 산업 협회 중앙회 지회 전국...,"[박람회, 창업, 대구경북지회, 협회, 산업, 비즈니스, 엑스코, 주최, 전시장, 참가]","[(박람회, 0.5253), (창업, 0.5143), (대구경북지회, 0.4811)..."
333,NH농협카드 CI\n\nNH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 ...,NH농협카드 CI NH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 편의성...,NH농협카드 CI NH농협카드 학생 상공인 예비 창업자 고객 데이터 활용 편의 금융...,"[nh농협카드, 카드, 비즈니스, 활용, 농협, 김용환, 사용, 데이터, 이용, 디지털]","[(nh농협카드, 0.6054), (카드, 0.4322), (비즈니스, 0.3619..."
349,김경태기자 구독 구독중 이전 다음\n\n(수원=연합뉴스) 김경태 기자 = 30일 성...,구독 구독중 이전 다음 30일 성남시 분당구 판교 스타트업캠퍼스에서 2023 경기 ...,구독 구독 이전 다음 성남시 분당구 판교 스타트업 캠퍼스 스타트업 위크 이미지 확대...,"[개막식, 성남시, 콘퍼런스, 개막, 김동연, 김동환, 스타트업, 참석자, 가이아데...","[(개막식, 0.6042), (성남시, 0.5616), (콘퍼런스, 0.5595),..."
344,사진/부산보건대학교\n\n부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로...,사진/부산보건대학교 부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로그램으...,부산보건대학교 부산보건대학교 이틀간 혁신 지원 사업 프로그램 창업 캠프 창업 캠프 ...,"[부산보건대, 부산보건대학교, 안내, 직업인, 전문, 참가, 대학, 출전, 경영, ...","[(부산보건대, 0.6779), (부산보건대학교, 0.6229), (안내, 0.53..."

In [ ]:
df_20

,source,title,content,url,published_at,collected_at,status,category,summary,clean_content,analysis_content,keybert_keyword_scores,keybert_keywords,bertopic_topic
24,이투데이,"LG전자, '금성사 창업 정신 계승' 사내벤처 프로그램 ‘스튜디오341’ 가...",금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명\n\n미래 산업 분야 사업 ...,https://www.etoday.co.kr/news/view/2253133,2023-05-30 00:00:00,2026-05-26 10:47:22,수집,창업트렌드,금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명\n\n미래 산업 분야 사업 ...,금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명 미래 산업 분야 사업 아이디...,금성사 설립 연지동 번지 명명 미래 산업 분야 사업 아이디어 국내 임직원 선발 스타...,"[(스타트업, 0.5764), (벤처, 0.5478), (혁신, 0.5211), (...","[스타트업, 벤처, 혁신, 스튜디오, 창업, 모집, 임직원, 로봇, 현업, 기업]",18
6,식품저널 foodnews,"프랜차이즈산업협회, 올해 4회 창업 박람회 연다",‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,http://www.foodnews.co.kr/news/articleView.htm...,2023-02-28 00:00:00,2026-05-26 10:46:53,수집,창업트렌드,‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...,IFS 프랜차이즈 창업 박람회 지난해 코엑스 프랜차이즈 산업 협회 중앙회 지회 전국...,"[(박람회, 0.5253), (창업, 0.5143), (대구경북지회, 0.4811)...","[박람회, 창업, 대구경북지회, 협회, 산업, 비즈니스, 엑스코, 주최, 전시장, 참가]",19
333,스트레이트뉴스,"농협카드, 소상공인·예비창업자에 데이터 제공",NH농협카드 CI\n\nNH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 ...,https://www.straightnews.co.kr/news/articleVie...,2023-07-30 00:00:00,2026-05-26 11:51:58,수집,창업트렌드,NH농협카드 CI\n\nNH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 ...,NH농협카드 CI NH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 편의성...,NH농협카드 CI NH농협카드 학생 상공인 예비 창업자 고객 데이터 활용 편의 금융...,"[(nh농협카드, 0.6054), (카드, 0.4322), (비즈니스, 0.3619...","[nh농협카드, 카드, 비즈니스, 활용, 농협, 김용환, 사용, 데이터, 이용, 디지털]",1
349,연합뉴스,판교서 '스타트업 위크' 개막…창업·기술·투자의 만남,김경태기자 구독 구독중 이전 다음\n\n(수원=연합뉴스) 김경태 기자 = 30일 성...,https://www.yna.co.kr/view/AKR2023103013510006...,2023-10-30 00:00:00,2026-05-26 11:52:28,수집,창업트렌드,경기도경제과학진흥원이 '스타트업 판교에서 유니콘으로'를 주제로 주최한 이번 행사는 ...,구독 구독중 이전 다음 30일 성남시 분당구 판교 스타트업캠퍼스에서 2023 경기 ...,구독 구독 이전 다음 성남시 분당구 판교 스타트업 캠퍼스 스타트업 위크 이미지 확대...,"[(개막식, 0.6042), (성남시, 0.5616), (콘퍼런스, 0.5595),...","[개막식, 성남시, 콘퍼런스, 개막, 김동연, 김동환, 스타트업, 참석자, 가이아데...",22
344,메트로신문,"부산보건대, 혁신지원사업 프로그램 창업캠프 성료",사진/부산보건대학교\n\n부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로...,http://www.metroseoul.co.kr/article/2023092650...,2023-09-26 00:00:00,2026-05-26 11:52:18,수집,창업트렌드,사진/부산보건대학교\n\n부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로...,사진/부산보건대학교 부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로그램으...,부산보건대학교 부산보건대학교 이틀간 혁신 지원 사업 프로그램 창업 캠프 창업 캠프 ...,"[(부산보건대, 0.6779), (부산보건대학교, 0.6229), (안내, 0.53...","[부산보건대, 부산보건대학교, 안내, 직업인, 전문, 참가, 대학, 출전, 경영, ...",16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
907,공감신문,"[이슈공감]""IFS 프랜차이즈 창업박람회, 포스트 코로나 그 자체""…상반...",2023년 상반기 IFS 프랜차이즈 창업박람회가 30일 삼성 코엑스몰에서 개최됐다....,https://www.gokorea.kr/news/articleView.html?i...,2023-03-30 00:00:00,2026-05-26 14:08:48,수집,창업트렌드,2023년 상반기 IFS 프랜차이즈 창업박람회가 30일 삼성 코엑스몰에서 개최됐다....,2023년 상반기 IFS 프랜차이즈 창업박람회가 30일 삼성 코엑스몰에서 개최됐다....,상반기 IFS 프랜차이즈 창업 박람회 삼성 코엑스몰 공감 신문 상반기 창업 트렌드 ...,"[(박람회, 0.5736), (상반기, 0.5045), (코엑스몰, 0.484), ...","[박람회, 상반기, 코엑스몰, 전시, 전시회, 실내, 참가, 업체, 오전, 요즘]",29
316,한국경제,"'창업의 달인' 노정석 ""스타트업, 테슬라처럼 해야 살아남는다""","한국벤처캐피탈협회 기술세미나\n\n노정석 비팩토리 대표. 사진=김영우 기자\n\n""...",https://www.hankyung.com/it/article/202304276728i,2023-04-27 00:00:00,2026-05-26 11:51:28,수집,창업트렌드,국내 스타트업 중에서는 처음으로 구글에 인수된 블로그 회사 태터앤컴퍼니를 비롯해 일...,한국벤처캐피탈협회 기술세미나 노정석 비팩토리 대표. 사진 앞으로 스타트업은 테슬라처...,한국벤처캐피탈협회 기술 세미나 노정석 비팩토리 스타트업 테슬라 노정석 비팩토리 인공...,"[(한국벤처캐피탈협회, 0.6745), (협회장, 0.551), (회원사, 0.51...","[한국벤처캐피탈협회, 협회장, 회원사, 세미나, 임직원, 협회, 기업부, 회사, 벤...",-1
41,아시아경제,"JYP 작곡가 출신 창업자, 반려견 화식 사료로 두 번째 '히트'",강아지 화식 사료 브랜드 '씽크라이크펫'\n\n맞춤형 정기 구독으로 블루오션 개척\...,https://view.asiae.co.kr/article/2023092620402...,2023-09-30 00:00:00,2026-05-26 10:47:59,수집,창업트렌드,아무도 가보지 않은 길이라 생산 공정을 만들기까지 우여곡절을 겪었지만 덕분에 트렌드...,강아지 화식 사료 브랜드 씽크라이크펫 맞춤형 정기 구독으로 블루오션 개척 가족인 반...,강아지 화식 사료 브랜드 씽크라이크펫 맞춤 정기 구독 블루오션 개척 가족 반려견 건...,"[(제조사, 0.5739), (씽크라이크펫, 0.5606), (클로이, 0.5523...","[제조사, 씽크라이크펫, 클로이, 핏불이, 클로, 제품, 이전, 설립, 나스닥, 강아지]",1
642,디지털타임스,"인덕대학교 캠퍼스타운, 초기 창업 지원 `2023년 창업아카데미` 성료",[저작권자 ⓒ디지털타임스 무단 전재-재배포 금지]\n\n인덕대학교 캠퍼스타운사업단(...,https://www.dt.co.kr/contents.html?article_no=...,2023-09-27 00:00:00,2026-05-26 12:59:19,수집,창업트렌드,"참여 수강생은 ""이번 인덕대학교 캠퍼스타운 창업 아카데미는 CEO 비즈니스 매너나 ...",인덕대학교 캠퍼스타운사업단 은 2023년 캠퍼스타운 창업아카데미 프로그램을 성황리에...,인덕대학교 캠퍼스 타운 사업단 캠퍼스 타운 창업 아카데미 프로그램 성황 마무리 캠퍼...,"[(아카데미, 0.6285), (비즈니스, 0.5322), (캠퍼스, 0.5231)...","[아카데미, 비즈니스, 캠퍼스, 실전, 연출, 사업단, 대학교, 창업자, 기업, 강의]",9
626,일반기사,"대전혁신센터, 30일 스타트업 글로벌 진출 위한 ‘대전창업포럼’",제81회 대전창업포럼 포스터. (대전혁신센터 제공)/뉴스1\n(대전ㆍ충남=뉴스1) ...,https://n.news.naver.com/mnews/article/421/000...,2023-06-27 11:18:49,2026-05-26 12:58:40,수집,창업트렌드,제81회 대전창업포럼 포스터. (대전혁신센터 제공)/뉴스1\n(대전ㆍ충남=뉴스1) ...,제81회 대전창업포럼 포스터. /뉴스1 대전시는 오는 30일 대전 본원에서 ‘스타트...,대전 창업 포럼 포스터 뉴스1 대전시 대전 본원 스타트업 성공 글로벌 진출 효율 조...,"[(포럼, 0.5901), (포스터, 0.5617), (글로벌리제이션, 0.5438...","[포럼, 포스터, 글로벌리제이션, 홈페이지, 글로벌, 대전시, 협회, 협업, 스타트...",32

In [ ]:
# df_20의 0번째 행에 있는 keybert_keyword_scores 컬럼 값 확인
df_20.loc[626, "keybert_keyword_scores"]

[('포럼', 0.5901),
 ('포스터', 0.5617),
 ('글로벌리제이션', 0.5438),
 ('홈페이지', 0.5398),
 ('글로벌', 0.4564),
 ('대전시', 0.4558),
 ('협회', 0.4496),
 ('협업', 0.4487),
 ('스타트업', 0.4418),
 ('파트너스', 0.4383)]

#### BERTopic 작업 수행
- clean_content 컬럼 사용

In [ ]:
!pip install bertopic
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
import pandas as pd


# ============================================================
# BERTopic 토픽 모델링
# ============================================================
# 사용 컬럼:
# - clean_content
#   → 노이즈 제거는 완료되었지만 문장 형태가 유지된 뉴스 본문
#
# 목적:
# - 뉴스 본문을 의미적으로 비슷한 토픽끼리 묶는다.
# - 토픽별 대표 키워드를 추출한다.
#
# 주의:
# - df_20은 20개 샘플 데이터이므로 실제 전체 데이터보다 토픽 품질은 낮을 수 있음
# ============================================================


# ============================================================
# 1. BERTopic 토픽 키워드 추출용 토크나이저
# ============================================================
# clean_content 문장은 그대로 BERTopic에 입력하되,
# 토픽 대표 단어를 뽑을 때는 Kiwi 형태소 분석 + 불용어 제거를 적용한다.
# 이 코드에서는 일반명사(NNG)만 토픽 키워드 후보로 사용한다.
# ============================================================

def kiwi_tokenizer(text):
    tokens = []

    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사만 사용
        if pos == "NNG":

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            tokens.append(word)

    return tokens


# ============================================================
# 2. BERTopic 입력 데이터 준비
# ============================================================
# clean_content 컬럼에서 비어 있지 않은 문장만 사용
# ============================================================

df_bertopic = df_20[df_20["clean_content"].notna()].copy()
df_bertopic = df_bertopic[df_bertopic["clean_content"].str.strip() != ""].copy()

docs = df_bertopic["clean_content"].tolist()

print("BERTopic에 입력할 문서 개수:", len(docs))


# ============================================================
# 3. CountVectorizer 설정
# ============================================================
# 토픽별 대표 키워드를 뽑을 때 사용할 토큰화 방식 지정
# ============================================================

vectorizer_model = CountVectorizer(
    tokenizer=kiwi_tokenizer,
    token_pattern=None,
    ngram_range=(1, 1),
    min_df=1,
    max_df=0.9
)


# ============================================================
# 4. 임베딩 모델 설정
# ============================================================
# 한국어 문장 의미를 벡터로 변환하기 위한 다국어 임베딩 모델 사용
# ============================================================

embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")


# ============================================================
# 5. UMAP / HDBSCAN 설정
# ============================================================
# df_20은 샘플 데이터 20개만 사용하므로,
# 작은 데이터에서도 토픽이 생성될 수 있도록 값을 낮게 설정
# ============================================================

umap_model = UMAP(
    n_neighbors=5,
    n_components=2,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

hdbscan_model = HDBSCAN(
    min_cluster_size=2,
    min_samples=1,
    metric="euclidean",
    prediction_data=True
)


# ============================================================
# 6. BERTopic 모델 생성 및 학습
# ============================================================

topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)


# ============================================================
# 7. df_20에 BERTopic 결과 저장
# ============================================================
# topic 번호를 원본 df_20의 해당 행에 다시 저장
# ============================================================

df_bertopic["bertopic_topic"] = topics

# df_20에 bertopic_topic 컬럼 생성
df_20["bertopic_topic"] = None

# clean_content가 존재했던 행에만 topic 결과 저장
df_20.loc[df_bertopic.index, "bertopic_topic"] = df_bertopic["bertopic_topic"]


# ============================================================
# 8. 토픽 정보 확인
# ============================================================

topic_info = topic_model.get_topic_info()

print("생성된 토픽 정보:")
display(topic_info)

# df_20 결과 확인
df_20[["clean_content", "bertopic_topic"]].head()

Requirement already satisfied: bertopic in /usr/local/lib/python3.12/dist-packages (0.17.4)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.43)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.5.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.16.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.11.0+cu128)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.25.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.9.6)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.8.90)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.7.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.4.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
BERTopic에 입력할 문서 개수: 100

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-27 07:45:02,659 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/4 [00:00<?, ?it/s]

2026-05-27 07:45:03,135 - BERTopic - Embedding - Completed ✓
2026-05-27 07:45:03,138 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-27 07:45:03,245 - BERTopic - Dimensionality - Completed ✓
2026-05-27 07:45:03,246 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-27 07:45:03,264 - BERTopic - Cluster - Completed ✓
2026-05-27 07:45:03,267 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-27 07:45:06,763 - BERTopic - Representation - Completed ✓

생성된 토픽 정보:

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5,-1_쇼핑몰_온라인_추천_게임,"[쇼핑몰, 온라인, 추천, 게임, 택배, 사업, 지원, 확인, 교육, 솔루션]",[인공지능 기반의 MICE 및 콘텐츠 전문 기업 디노마드가 ‘2023 게임 스타트업...
1,0,6,0_교육_과정_사회_경제,"[교육, 과정, 사회, 경제, 수료, 외식, 실무, 강사, 예비, 스쿨]",[경기도경제과학진흥원 전경/사진제공 경과원 경기도와 경기도경제과학진흥원은 신산업 분...
2,1,5,1_카드_데이터_소비_사료,"[카드, 데이터, 소비, 사료, 현황, 일자, 농협, 화식, 고객, 분석]",[NH농협카드 로고©열린뉴스통신ONA NH농협카드는 학생·소상공인·예비창업자 고객의...
3,2,5,2_그룹_기부_유니콘팩토리_국민,"[그룹, 기부, 유니콘팩토리, 국민, 실천, 경영, 평가, 임대, 창업주, 행정학]",[【청년일보】 부영그룹은 이중근 창업주가 3년 만에 경영 일선에 복귀하며 회장으로 ...
4,3,4,3_치킨_베이글_새해_장비,"[치킨, 베이글, 새해, 장비, 점포, 선정, 메뉴, 소재, 카페, 부품]",[사업화자금 최대 2억원 및 융자 등 연계지원으로 글로벌 기업 육성 중소벤처기업부 ...
5,4,4,4_해외_중견_스타트업_기업,"[해외, 중견, 스타트업, 기업, 협력, 진출, 도시, 기술, 허브, 지원]",[해외 세일즈 지원 분야별 오픈 이노베이션 기회 확대 글로벌 네트워킹 강화 미래성장...
6,5,4,5_학생_탐방_대학_방문,"[학생, 탐방, 대학, 방문, 글로벌, 사관학교, 국제, 학과, 청년, 취창업]",[아시아 창업도시 구축을 위한 제9회 국제 학생창업 콘퍼런스 가 31일 동명대에서 ...
7,6,4,6_교육_먼지_탁구_청년,"[교육, 먼지, 탁구, 청년, 미세, 차량, 불편, 계층, 물류, 사랑]",[【 청년일보 】 중소벤처기업부는 미래 창업자 및 준비된 창업자를 양성하기 위해 다...
8,7,3,7_로봇_조성_제조_첨단,"[로봇, 조성, 제조, 첨단, 스타트업, 세계, 기업, 산업, 투자, 바이오]","[오세훈 서울시장, 서울 창업정책 2030 발표6 0 오세훈 서울시장이 21일 서울..."
9,8,3,8_혁신_수도_투자_제조,"[혁신, 수도, 투자, 제조, 생태, 스타트업, 계획, 추진, 글로벌, 펀드]",[‘창업투자’ 류중희 퓨처플레이 대표 민간로켓 ‘이노스페이스’ 등 투자 “앞으로 1...
10,9,3,9_경영_과정_금융_아카데미,"[경영, 과정, 금융, 아카데미, 타운, 캠퍼스, 프로그램, 비즈니스, 강의, 수강]",[인덕대학교 캠퍼스타운사업단 은 2023년 캠퍼스타운 창업아카데미 프로그램을 성황리...
11,10,3,10_기사_연주_정원_소음,"[기사, 연주, 정원, 소음, 파도, 밴드, 복사, 시간, , ]","[소음의 정원 에 다시 밀려온 27년 만의 파도 노이즈가든 윤병주, 30년의 시간을..."
12,11,3,11_브랜드_정보_창업자_예비,"[브랜드, 정보, 창업자, 예비, 프랜차이즈, 연쇄, 창업가, 확인, 수집, 경험]",[2011년 패션 업체 어썸브랜드를 창업한 이두진 대표. 2016년 옐로모바일에 매...
13,12,3,12_포럼_주제_탄소_테크,"[포럼, 주제, 탄소, 테크, 무역, 중립, 오픈, 세션, 혁신, 스타트업]",[혁신의 트렌드 : 반도체에서 바이오 혁명까지 주제 기조연설 요아브 니산코헨 타워세...
14,13,3,13_가상_기술_사용자_현실,"[가상, 기술, 사용자, 현실, 지능, 인공, 모델, 사용, 활용, 공간]",[이창수 올거나이즈 대표 최근 글로벌 인공지능 업계는 흐름을 따라잡기 어려울 정도로...
15,14,3,14_혁신_제조_수도_생태,"[혁신, 제조, 수도, 생태, 계획, 투자, 추진, 특강, 펀드, 문화]",[배움의 끝은 결국 나눔 전 IBM 강성권 박사 회고록 발간 왜 배우는가. AI가 ...
16,15,3,15_가맹점주_보험_보장_리그,"[가맹점주, 보험, 보장, 리그, 프로모션, 아이센스, 설명회, 본사, 인테리어, ...",[파스타 브랜드 미태리가 가맹점 창업을 희망하는 예비 점주들의 성공을 위해 트렌드에...
17,16,3,16_창업가_네트워킹_캠프_직장인,"[창업가, 네트워킹, 캠프, 직장인, 전문, 프로그램, 스쿨, 현장, 교육, 참가자]",[중소벤처기업부는 29일 서울 강남구 섬유센터빌딩에서 제1회 혁신창업스쿨 콘퍼런스 ...
18,17,3,17_세대_골격_시니어_활동,"[세대, 골격, 시니어, 활동, 취미, 이사, 인구, 이상, 실버, 한의사]",[칼럼 6·3 지방선거 당선자에게 고하는 미래 농업 선거철마다 쏟아지는 화려한 개발...
19,18,2,18_사내_전자_벤처_육성,"[사내, 전자, 벤처, 육성, 선발, 임직원, 아이디어, 도전, 스튜디오, 역량]",[LG전자가 금성사 창업 당시의 도전·혁신 정신을 계승할 사내벤처 발굴과 육성에 나...
20,19,2,19_박람회_프랜차이즈_커피_협회,"[박람회, 프랜차이즈, 커피, 협회, 희망자, 엑스포, 행사, 참관, 전시회, 역대]",[‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코...
21,20,2,20_직무_센터_중장년_워크숍,"[직무, 센터, 중장년, 워크숍, 취업, 관내, 청년, 캠프, 입주, 일자리]",[대구 계명문화대학교 중장년 기술창업센터와 경산 중장년 기술창업센터가 22일 호텔인...
22,21,2,21_중장년_센터_계명_워크숍,"[중장년, 센터, 계명, 워크숍, 문화, 합동, 기술, 입주, 노하우, 발전]",[호텔인터불고 대구에서 열린 2023 경산‧계명문화 중장년 기술창업센터 중장년 합동...
23,22,2,22_위크_스타트업_부지사_수입,"[위크, 스타트업, 부지사, 수입, 강연, 투자, 콘서트, 새싹, 캠퍼스, 기조]",[동국대학교 창업기술원이 협력기관인 ㈜오퍼스이앤씨와 함께 유망 스타트업 ㈜써드웍스에...
24,23,2,23_콘텐츠_선도_오픈_기업,"[콘텐츠, 선도, 오픈, 기업, 주제, 포럼, 지역, 초기, 사업, 세션]",[광주지역 문화콘텐츠 선도기업들이 지역 스타트업 성장을 지원하기 위해 발벗고 나섰다...
25,24,2,24_교육_재단_우수_국제,"[교육, 재단, 우수, 국제, 정신, 선정, 기업가, 대학, 프로그램, 학과]",[구인혁 우송대 엔디컷국제대학 글로벌융합비즈니스학과 교수 우송대는 엔디컷국제대학 글...
26,25,2,25_캠프_학생_시상식_경진,"[캠프, 학생, 시상식, 경진, 디자인, 특허, 재산, 대회, 센터장, 교내]",[조선이공대 PEARL LTE+ 창업캠프’ 참가자들이 기념촬영하고 있다. /사진제공...
27,26,2,26_작전_특검_내란_합참,"[작전, 특검, 내란, 합참, 사령관, 의장, 보고, 진술, 종합, 계엄]",[404 페이지를 찾을 수 없습니다 죄송합니다. 요청하신 페이지를 찾을 수 없습니다...
28,27,2,27_편의점_아이템_유행_전문점,"[편의점, 아이템, 유행, 전문점, 샐러드, 점주, 수요, 본사, 점포, 계약]","[김진희 서울신용보증재단 자영업지원센터 책임 전문위원. 창업을 할 때, 유행 아이템..."
29,28,2,28_세미나_사례_소개_진흥원,"[세미나, 사례, 소개, 진흥원, 생태, 협력, 컨퍼런스, 산업, 청중, 우수]","[지난 28일, 인천광역시가 주최하고 인천창조경제혁신센터가 전담하며 주식회사 더이노..."
30,29,2,29_시뮬레이션_신문_시식_시간,"[시뮬레이션, 신문, 시식, 시간, 업체, 공감, 프랜차이즈, 박람회, 전시, 실내]",[창업전문 에듀테크 기업 메인콘텐츠가 지난 24~25일 양일간 강원도 세인트존스호텔...
31,30,2,30_해양_수산_설명회_소개,"[해양, 수산, 설명회, 소개, 수산부, 단장, 청년, 동아리, 참가자, 선배]",[2일 입석홀에서 해양수산부 주최. 조선대는 6월 2일 오후 교내 입석홀에서 ‘찾아...
32,31,2,31_테크_건축_건설_공유,"[테크, 건축, 건설, 공유, 주거, 공간, 세미나, 전시회, 건물, 특별]",[미디어뉴테크대전 포스터. 대구시 제공 대구시와 과학기술정보통신부가 공동 주최하는 ...
33,32,2,32_포럼_세션_글로벌_포스터,"[포럼, 세션, 글로벌, 포스터, 토크, 효율, 조직, 신청, 강연, 성공]",[제81회 대전창업포럼 포스터. /뉴스1 대전시는 오는 30일 대전 본원에서 ‘스타...

                                         clean_content bertopic_topic
24   금성사 설립된 ‘부산 연지동 341번지’에서 따와 명명 미래 산업 분야 사업 아이디...             18
6    ‘2022 제53회 IFS프랜차이즈 창업 박람회’가 지난해 10월 20~23일 코엑...             19
333  NH농협카드 CI NH농협카드는 학생·소상공인·예비창업자 고객의 데이터 활용 편의성...              1
349  구독 구독중 이전 다음 30일 성남시 분당구 판교 스타트업캠퍼스에서 2023 경기 ...             22
344  사진/부산보건대학교 부산보건대학교는 지난 21~22일 이틀간 혁신지원사업 프로그램으...             16

In [ ]:
df_20[
    [
        "clean_content",
        "analysis_content",
        "keybert_keywords",
        "bertopic_topic"
    ]
].head()

,clean_content,analysis_content,keybert_keywords,bertopic_topic
79,39세 이하 1인 무주택 청년창업인 대상 5월 4일까지 접수 서울 관악구는 청년 창...,이하 주택 청년 창업 접수 관악구 청년 창업 안정 주거 사무 공간 자립 청년 맞춤 ...,"[신청자, 시민, 민간, 체결, 계약, 공공, 일자리, 모집, 소득, 주택]",2
105,청년 1인가구 공공과 사회 가 함께 돌보는 사회시스템 모색 생활환경·경제기반·사회적...,청년 가구 공공 사회 사회 시스템 모색 생활 환경 경제 기반 사회 관계 사회 안전망...,"[세대, 사회, 변화, 집단, 인구, 감소, 생활환경, 미래, 삼포세대, 포기]",0
677,"독재자 히틀러, 국가 통제를 위한 국민차를 꿈꾸다. 포르셰, 히틀러를 만나 폭스바겐...",독재자 히틀러 국가 통제 국민 포르셰 히틀러 폭스바겐 일반 독일 가정 성인 어린이 ...,"[히틀러, 독재자, 자유, 유럽, 대전, 독일어, 독일, 폭스바겐, 세기, 역사]",19
90,선거판 강타 ‘동남풍’ 막전막후 영남권에서 시작된 동남풍이 이번 6·3 지방선거 승...,선거 강타 동남풍 막후 영남 시작 동남풍 지방 선거 승패 변곡점 텃밭 무력 국민 보...,"[더불어민주당, 이진숙, 김부겸, 수렴, 김상욱, 경북도당, 오빠, 박형준, 여야,...",1
367,"기사내용 요약 중기부, 2020년 기준 창업기업 실태조사 발표 창업기업 307만16...",기사 내용 요약 중기 기준 창업 기업 실태 조사 창업 기업 기술 기반 전체 고용 인...,"[창업진흥원, 통계청, 벤처, 중장년, 보유, 등록부, 창업, 이전, 산업, 예년]",22

In [ ]:
topic_info = topic_model.get_topic_info()
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,6,-1_아동_센터_사업_지원,"[아동, 센터, 사업, 지원, 과일, 협회, 예술, 지역, 문화, 혁신]",[전국 1인 창조기업 중 11.5% 만이 ‘1인 창조기업 지원사업’ 지원을 받고 있...
1,0,6,0_청년_정책_가구_통합,"[청년, 정책, 가구, 통합, 특위, 고립, 사회, 취업, 표현, 은둔]",[김한길 국민통합위원장은 31일 청년 1인가구가 좀 더 건강하고 안정적인 환경에서 ...
2,1,4,1_후보_선거_보수_국민,"[후보, 선거, 보수, 국민, 갈등, 결집, 정치, 여론, 조정, 오차]",[칼럼 6·3 지방선거 당선자에게 고하는 미래 농업 선거철마다 쏟아지는 화려한 개발...
3,2,4,2_주택_자립_가구_디지털,"[주택, 자립, 가구, 디지털, 임대, 준비, 민간, 청년, 소득, 보호]",[본문 ‘나이팅게일 하우징’ 프로젝트로 만들어진 아파트에 사는 엘리자베스의 집. 1...
4,3,4,3_산업_수소_도시_원장,"[산업, 수소, 도시, 원장, 엑스포, 기술, 지원, 탄소, 경제, 조성]",[춘천시가 창업엑스포 개최를 위한 본격적인 행보에 나선다. 시는 이달 중으로 202...
5,4,4,4_동아리_아이디어_학생_수상,"[동아리, 아이디어, 학생, 수상, 대회, 경진, 센터, 보육, 대학, 안전]",[계원예대는 24일 경기창조경제혁신센터에서 진행된 제9회 수도권/강원권 전문대학연합...
6,5,4,5_커피_카페_가맹점_아이스크림,"[커피, 카페, 가맹점, 아이스크림, 상권, 주류, 브랜드, 프로모션, 가맹, 오픈]",[커피숍창업 프랜차이즈 크레이저커피 는 체인점 개설 희망자들을 대상으로 창업비용 할...
7,6,4,6_작심_건물주_케이스_운영,"[작심, 건물주, 케이스, 운영, 오픈, 브랜드, 돌파, 고기, 가능, 무한]",[인터뷰365 디저트 프랜차이즈 ‘황제탕후루’가 1인 창업 시스템을 지원한다고 밝혔...
8,7,4,7_주주_지분_최대_매각,"[주주, 지분, 최대, 매각, 바이오, 경영, 창조, 기업, 결정, 이사]","[노치환 도의원, 1인 창조기업 육성에 관한 조례 제정 노치환 경남도의원 경남도의회..."
9,8,4,8_입주_폐광_주민_기업,"[입주, 폐광, 주민, 기업, 모집, 지역, 이상, 지구, 삼면, 진흥]",[광진경제허브센터 운영사 엔슬파트너스가 2023년 광진경제허브센터에 새로 입주할 창...
10,9,4,9_플루_제품_브랜드_화장품,"[플루, 제품, 브랜드, 화장품, 집수리, 호스트, 브이, 커머스, 플랫폼, 셀프]",[혼자 사는 1인 가구가 늘어나면서 최근 새로운 주거문화로 DIY족이 늘어나고 있다...
11,10,4,10_청년_지역_지원_정착,"[청년, 지역, 지원, 정착, 연계, 사업, 자원, 로컬, 지원금, 최종]",[사진제공 해남군 해남군은 서울시와 지역연계형 청년 창업지원사업 추진 협약을 체결하...
12,11,3,11_설명회_행사_채용_합동,"[설명회, 행사, 채용, 합동, 신문, 기사, 심사, 예비, 정보, 창업가]",[강화군 창업·일자리센터 ‘세대융합형 창업지원 사업’ 참여자 모집 이미지 인천 강화...
13,12,3,12_기술_인력_재료_최고,"[기술, 인력, 재료, 최고, 생성, 활용, 생산, 인재, 책임자, 나노]",[최근 취업난으로 창업 시장에 뛰어드는 사람들이 늘고 있다. 성공적인 창업을 위해서...
14,13,3,13_투자_수입_계약_주식회사,"[투자, 수입, 계약, 주식회사, 무역, 연계, 데이터, 유치, 패키지, 솔루션]",[동국대학교 창업기술원과 오퍼스이앤씨가 지난 27일 유망 스타트업 주식회사 써드웍스...
15,14,3,14_저가_상공인_자영업자_메뉴,"[저가, 상공인, 자영업자, 메뉴, 부담, 금리, 보험료, 가격, 인기, 어사]",[광주광역시청사. 광주광역시가 지속되는 경제위기 상황으로 경영에 어려움을 겪고 있는...
16,15,3,15_강의_자문_수강_여성,"[강의, 자문, 수강, 여성, 셀러, 아카데미, 세미나, 글로벌, 위원회, 모집]",[글로벌셀러아카데미 는 2월 ‘해외구매대행’ 창업과정 무료세미나를 개최한다고 밝혔다...
17,16,3,16_의결_기업_복수_국회,"[의결, 기업, 복수, 국회, 법안, 벤처, 고용, 주식, 토론, 평균]",[창업 창업기업 이 국내 300만개가 넘고 고용 인원은 360만명을 웃도는 것으로 ...
18,17,3,17_다단계_불법_피해_업체,"[다단계, 불법, 피해, 업체, 은퇴, 범죄, 노후, 보장, 영업, 점검]",[서울시가 은퇴계층을 상대로 한 불법 다단계 주의보를 발령했습니다. 시는 1960년...
19,18,3,18_피자_가격_선물_가성비,"[피자, 가격, 선물, 가성비, 영향, 지난해, 매출, 세트, 감소, 물가]",[가성비 vs 가심비 설 선물 양극화 ［충북일보］경기침체와 고물가 영향으로 설 선물...
20,19,2,19_우표_전쟁_자동차_차량,"[우표, 전쟁, 자동차, 차량, 국민, 보급, 보험료, 독재자, 상징, 저축]",[최대 3년간 고용·산재보험료 부담액의 50% 27일부터 신청 광주시청 0 광주시청...
21,20,2,20_작전_특검_합참_내란,"[작전, 특검, 합참, 내란, 사령관, 의장, 보고, 종합, 진술, 계엄]","[지도자의 자질은 미래를 말할 때 드러난다. 위기가 목전의 불을 가리키는 행위라면,..."
22,21,2,21_학생_성과_제도_대학,"[학생, 성과, 제도, 대학, 양성, 사업단, 국립, 구축, 인프라, 로컬]",[국립목포대 전경. 국립목포대학교의 3단계 산학연협력 선도대학 육성사업단 은 최근 ...
23,22,2,22_업종_기업_조사_고용,"[업종, 기업, 조사, 고용, 전체, 결과, 동네, 평균, 씨이오, 세탁]",[창업을 꿈꾸는 예비 창업자들이 가장 높은 관심을 가지는 업종은 무엇일까? 소상공인...
24,23,2,23_고객_마케팅_구매_노동,"[고객, 마케팅, 구매, 노동, 지수, 상품, 목적, 점포, 지식, 성공]",[꿈은 삶의 이정표이자 동력이다. 꿈은 곧 미래의 삶이다. 꿈은 그래서 소중하다. ...
25,24,2,24_총회_바닥재_음성_개발,"[총회, 바닥재, 음성, 개발, 주주, 인식, 언어, 엔터테인먼트, 지원, 서비스]",[이수만 SM엔터테인먼트 창업자 겸 전 총괄 프로듀서. 제공|SM엔터테인먼트 SM엔...
26,25,2,25_미디어_포럼_주제_센터,"[미디어, 포럼, 주제, 센터, 강연, 시장, 시민, 오픈, 중심, 다양]",[대전 1인 창조기업 지원센터가 ‘대전융합포럼 D-JSA ’을 개최했다. 대전융합포...
27,26,2,26_전년_대비_증가_매출액,"[전년, 대비, 증가, 매출액, 기업, 중소기업, 종사자, 조사, 기준, 고용]",[기술기반 22%... 30대 이하 청년층 창업기업 67.5만개 22.0% 차지 2...
28,27,2,27_창조_센터_기업_액셀러레이터,"[창조, 센터, 기업, 액셀러레이터, 쇼케이스, 투자, 행사, 고양, 유치, 지원]","[고양 1인창조기업지원센터, 맞춤형 창업교육 개최 고양산업진흥원이 운영하는 고양 1..."
29,28,2,28_프로그램_아이디어_융합_참여자,"[프로그램, 아이디어, 융합, 참여자, 사례, 기업가, 뮤지엄, 방문, 개발, 거주자]",[강화군창업·일자리센터는 오는 7월 2일까지 ‘세대융합형 창업지원 사업’ 참여자를 ...
30,29,2,29_동물_아이_카페_식탁,"[동물, 아이, 카페, 식탁, 살롱, 채식주의자, 건강, 소개, 베이킹, 우유]",[프랜차이즈 무국적식탁이 전국 24호점 달성을 기념해 창업 프로모션을 진행중이다. ...
31,30,2,30_데모_데이_서비스_심사,"[데모, 데이, 서비스, 심사, 선배, 사관, 학교, 스토리텔링, 큐레이션, 자취]",[신한은행은 소상공인들의 경영을 돕는 신한 소호 사관학교 26기 를 개강했다고 28...