# 작업위치 확인 및 변경
- 파일 불러오기 전 작업

In [ ]:
# 구글 드라이브 연결하기
from google.colab import drive
drive.mount('/content/drive')

# 현재 작업 위치 확인하기
import os
print(os.getcwd())

# 작업위치 변경하기
%cd /content/drive/MyDrive/Colab Notebooks/실전프로젝트

# data 폴더 내에 csv 파일 확인하기
import glob

csv_files = glob.glob("data/*.csv")

print("================================= 불러올 파일 확인 ====================================")
print("CSV 파일 개수:", len(csv_files))
print(csv_files[:5])

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/My Drive/Colab Notebooks/실전프로젝트
/content/drive/MyDrive/Colab Notebooks/실전프로젝트
================================= 불러올 파일 확인 ====================================
CSV 파일 개수: 2
['data/HBR_articles.csv', 'data/DBR_articles.csv']

## 재한팀 DBR,HBR 데이터 확인

In [ ]:
import pandas as pd

# 첫 번째 CSV 파일 불러오기
df_hbr = pd.read_csv(csv_files[0])

# 데이터 크기 확인
print("데이터 크기:", df_hbr.shape)

# 컬럼 확인
print("컬럼 목록:")
print(df_hbr.columns)

# 상위 5개 행 확인
df_hbr.tail()

데이터 크기: (2062, 7)
컬럼 목록:
Index(['title', 'content', 'url', 'category', 'published_date', 'source',
       'summary'],
      dtype='object')

,title,content,url,category,published_date,source,summary
2057,"이베르드롤라 CEO, 클린에너지에 올인한 이유",이니고 데 오리올 에 이바라 전 회장이 나에게 이베르드롤라\nIberdrola\n의...,https://www.hbrkorea.com/article/view/atype/ma...,지속가능성,2020. 11-12월호,HBR Korea,이니고 데 오리올 에 이바라 전 회장이 나에게 이베르드롤라
2058,"기업의 이윤 추구와 소셜 임팩트, 양립 불가능할까?",2019년\n미국의 비즈니스 라운드테이블\n이 '주주 자본주의'에서 '이해관계자 자...,https://www.hbrkorea.com/article/view/atype/di...,지속가능성,2020. 10. 8.,HBR Korea,이 '주주 자본주의'에서 '이해관계자 자본주의'로의 전환을 선언한 지 1년이 됐습니...
2059,필립모리스CEO가 말하는 ‘담배 연기 없는 미래’,2016년 필립모리스인터내셔널(PMI)은 전통적인 형태의 담배와 기타 가연성 담배 ...,https://www.hbrkorea.com/article/view/atype/di...,지속가능성,2020. 9. 14.,HBR Korea,2016년 필립모리스인터내셔널(PMI)은 전통적인 형태의 담배와 기타 가연성 담배 ...
2060,"고성장 추억 가진 한국기업, 지속가능성 접목 하려면?",이번\n4\n월 호\nSpotlight\n에서 가장 눈에 띄는 기사는\n‘CFO\n...,https://www.hbrkorea.com/article/view/atype/ma...,지속가능성,NaN,HBR Korea,보통 재무와 지속가능성은 서로 상반되는 개념이라고 생각하기 쉽기 때문에 이 두 개념...
2061,CFO도 사랑할 수 있는 지속가능성 모델을 찾아…,"Artwork Julie Dodd, Inner Beauty,\n2012 800+ p...",https://www.hbrkorea.com/article/view/atype/ma...,지속가능성,NaN,HBR Korea,"Artwork Julie Dodd, Inner Beauty,"

In [ ]:
df_hbr['content'][2]

'미국-이스라엘의 대이란 전쟁이 계속되는 가운데 이 전쟁이 세계 경제에 미칠 영향은 아직 불분명하다. 그 핵심에는 석유 문제가 자리하고 있다. 이란이 호르무즈 해협을 봉쇄하면서\n전 세계 석유 공급량의 약 5분의 1에 달하는 물량의 흐름이 막혔다\n. 유가는 이미 급등한 상태지만 해협 봉쇄가 장기화될 경우 그 파장은 훨씬 더 심각해질 수 있다.\n현재 상황과 앞으로의 전망을 짚어보기 위해 HBR은 에너지 산업 데이터를 분석하는\n뉴스레터\n＜코모디티 컨텍스트\nCommodity Context\n＞의 창립자이자 토론토대 멍크국제학대학원 강사인 석유 애널리스트 로리 존스턴과 대화를 나눴다.\nQ. 호르무즈 해협 봉쇄로 전 세계 석유 공급량의 20%가 흐르는 파이프가 막힌 셈이다. 지금까지 시장에서 빠져나간 석유의 규모와 그 영향을 어떻게 보는가? 만약 내일 당장 사태가 해결된다 해도 말이다.\nA. 이 문제는 두 가지 측면에서 살펴봐야 한다. 첫째는 생산이다. 호르무즈 해협이 막히면 이라크나 쿠웨이트 같은 나라들은 원유를 내보낼 곳이 없어져 생산을 강제로 중단해야 한다. 즉 일시적으로 유정을 닫아야 하는 상황이다. 내 추산으로는 현재 걸프 지역에서 생산이 중단된 물량이 하루 약 850만 배럴에 달하며 이는 전 세계 공급량의 8% 이상이다. 어마어마한 양이다. 설령 지금 당장 해협이 열린다 해도 생산을 재개해 물량을 선적하기까지 몇 주에서 한두 달은 걸릴 것이다.\n둘째는 공급이다. 하루 약 2000만 배럴, 15일치를 합산하면 3억 배럴에 달하는 석유 제품이 걸프 지역에서 수출되지 못하고 있다. 걸프에서 아시아로 이어지는 석유 흐름에 커다란 공백이 생긴 것이다.\n세계 석유 시스템의 본질은 끊임없이 흘러야 하는 \'유동적인 화학 반응 장치\'라는 점을 기억해야 한다. 흐름이 일정하게 유지돼야 하는데 흐름 속도에 큰 변화가 생기면 시스템 전체에 연쇄적인 혼란이 발생한다. 이 공백이 심각한 이유는 걸프에서 출항한 유조선이 육지에 닿을 때까지도 시간이 필요하기 때문이다. 그 이후에야 공백이 본격적으로 현지 가용 공급량을 강타하기 시작할 것이다. 그리고 바로 그때부터 재고가 빠르게 고갈될 것이다.\n아시아 정유업체들의 선제적 대응도 주목해야 한다. 정유 시설은 일단 가동을 중단하면 재가동까지 몇 주에서 한 달이 걸리고 비용도 많이 들기 때문에 업체들은 공급 원유 투입량을 미리 줄여 가동 가능 기간을 늘리고 있다. 이는 일주일이나 이주일 후 공백이 본격화될 때 어떤 일이 벌어질지를 미리 보여주는 신호다. 아시아의 항공유 가격은 배럴당 200달러를 넘어섰고, 국제 해운을 움직이는 연료유는 통상 원유보다 낮은 가격에 거래되지만 프리미엄이 붙었다.\nQ. 이 상황이 장기화된다면 도미노처럼 파장이 점점 커질 것이다. 원료 공급이 바닥나면 결국 정유 시설도 가동을 멈출 수밖에 없다. 그 큰 도미노들이 쓰러지기 시작한다면 무엇이, 언제쯤 무너질까?\nA. 첫 번째 도미노는 앞서 말한 공백이 실제로 부딪히는 순간이다. 그 다음 큰 도미노는 시장의 반응이 될 것이다. 실물 희소성이 재고를 빠르게 고갈시키기 시작하면 우리가 직면한 현실을 피할 방법이 없다. 세계 금융 시장, 특히 선물 시장의 페이퍼 거래 쪽은 아직도 반신반의하는 분위기다. 설령 지금 그러한 상황이 펼쳐진다 해도 트럼프 대통령이 언제든 마무리 지을 것이라는 믿음이 뿌리 깊게 박혀 있다.\n트럼프 대통령의 외교 스타일, 특히 군사 개입에 있어서의 패턴을 보면 크고 화려하게, 마치 영화처럼 전면에 내세울 수 있는 무언가를 한 다음 재빨리 승리를 선언하고 이틀이나 사흘 만에 끝내버리는 경향이 있다. 솔직히 말하면 나 역시 그렇게 될 것이라 예상했다. 살면서 이런 상황을 보게 될 줄은 몰랐다.\n석유 시장에는 늘 과도한 경보가 넘친다. 나는 스스로를 과장하지 않는 분석가라고 생각해왔다. 보통은 시스템이 얼마나 놀랍고 역동적으로 충격에 적응하는지를 강조하는 편이었다. 하지만 이번 충격은 너무나 커서 시스템이 휘어지는 게 아니라 부러질 수도 있다는 우려가 든다. 그럼에도 많은 관찰자들이 이를 받아들이지 않으려 한다. 솔직히 말하자면 석유 업계에서는 늘 모든 것이 존폐의 위기라고 외쳐왔기 때문이다. 지금은 양치기 소년의 딜레마에 빠졌다.\nQ. ‘부러진다’는 게 구체적으로 어떤 의미인가?\nA. 이 맥락에서 \'부러진다\'는 것은 근본적으로 수요 파괴를 의미한다. 통상적으로 높은 가격은 공급업체들이 물류와 교역 경로를 재편해 같은 생산량으로도 더 많은 공급을 가능하게 하는 유인이 된다. 하지만 지금 우리가 직면한 손실 규모 앞에서는 그런 조치들로는 역부족이다. 이 상황이 계속된다면 가격은 실제로 물리적·물량적 수요 감소를 강제할 수준까지 치솟아야만 한다.\n이런 형태의 위기에서는 보통 나타나지 않는 현상이다. 흔히 보이는 패턴은 높은 가격이 장기간에 걸쳐 소비 지출을 갉아먹고, 우리가 흔히 이야기하는 경기 침체 문제를 야기하는 것이다. 하지만 지금의 상황은 가격 탄력성에 의한 수요 파괴, 즉 소비자가 구매를 \'선택하지 않는\' 것이 아니다. 소득 탄력성에 의한 수요 파괴, 즉 소비자가 구매할 \'능력이 없는\' 상황이다. 기름값이 비싸서 출근을 안 하는 게 아니라 일자리를 잃어서 출근을 못 하는 셈이다. 수요 파괴가 나타나는 가장 일반적인 형태다.\n해협 봉쇄가 지속된다면 비행기 수가 줄고 운전자가 줄어드는 수준까지 가격은 계속 오를 것이다. 지금 우리가 마주하고 있는 상황이 딱 그렇다.\nQ. 미국에서는 주유소 기름값 상승에 관심이 집중돼 있다. 석유 충격이 다른 방면에서는 어떤 파급 효과를 낳을 수 있을까? 다른 원자재에는 어떤 영향을 미칠까?\nA. 다른 분야로 넘어가기 전에 연료 이야기를 조금 더 하겠다. 경유·난방유·항공유, 이른바 \'중간 유분\' 시장은 휘발유보다 훨씬 더 심각한 압박을 받고 있다. 이 시장은 2022년 러시아의 우크라이나 침공 이후 줄곧 극도로 빡빡한 상태였고, 그 이후 석유 제품 시장에서 공급 부족의 핵심 요인으로 작용해왔다. 실제로 작년 12일 전쟁 당시 원유 가격이 급등했지만 경유 가격은 훨씬 더 큰 폭으로 올랐다. 크랙 스프레드\ncrack spread\n, 즉 경유와 원유의 가격 차이는 2월 초 배럴당 30달러 수준이었는데 현재는 거의 70달러에 달한다.\n휘발유 가격 상승은 가계 살림을 압박하고 정치적으로도 매우 민감한 문제다. 하지만 중간 유분이 경제적으로는 훨씬 더 중요하다. 운송비, 화물비, 장보기 비용, 택배비, 항공료 등 경제 전반이 여기에 달려 있기 때문이다. 특히 인플레이션 압력 가능성을 논할 때 훨씬 더 중요한 경제적·구조적 연료다.\n중앙은행들이 인플레이션 압력을 점검할 때, 소비자 기대 심리는 휘발유 가격을 통해 가늠하겠지만 구조적 인플레이션 영향을 살피는 데는 경유를 주로 들여다볼 것이다.\nQ. 가격 상승이 운송비 및 물가 상승으로 이어지기까지 얼마나 걸릴까?\nA. 결국 사람들이 이 상황이 언제 끝날 것이라고 보느냐의 문제다. 아직은 지속적인 충격으로 받아들이는 분위기는 아닌 것 같다. "아직은 운임을 올리지 말자, 우선 감당해보자"는 식으로 버티는 곳들이 많다. 하지만 한두 달이 더 이어진다면 공급망 전반에 비용을 전가하지 않을 수 없게 된다. 첫 한 달은 주로 해운 마진 잠식으로 나타날 것이다. 두세 달째 접어들면 고객에게 운임을 올려 마진을 회복하려 할 것이다. 대략 3개월 후부터 실질적인 여파가 본격적으로 나타나기 시작할 것이다.\n가격이 계속 높게 유지된다면 연준도 이를 예의주시할 것이다. 그 끝이 어디로 향하는지 보이지 않는가? 호주 중앙은행은 금리를 인상했다. 미국에서는 금리 인상까지는 아니더라도 추가 인하는 없다는 분위기다.\nQ. 중앙은행들은 러시아의 우크라이나 침공 후 금리 인상에 뒤처졌다는 비판을 받은 바 있다.\nA. 2022년의 경험이 여기서 매우 중요한 시사점을 준다. 통상 중앙은행은 에너지와 식품 가격의 변동을 무시한다. 이것이 자신들이 목표로 삼는 기저 인플레이션 압력을 제대로 반영하지 않는다고 보기 때문이다. 그런데 2022년에는 인플레이션 압력이 이미 커지고 있는 상황에서 에너지 가격 충격까지 겹쳤다. 이제는 더 이상 주유소 가격을 무시할 수 없다는 우려가 생겼다. 소비자 인플레이션 기대 심리가 흔들릴 수 있고 1970년대 상황이 재연될 수 있다는 공포였다.\n대부분의 사람들은 구리나 밀의 시세를 모른다. 하지만 출근길에 주유소 간판을 수도 없이 지나치니 기름값은 누구나 안다. 다른 모든 것이 2%밖에 안 오르더라도 기름값이 25% 오르면 모든 것이 25% 오른다고 느끼기 쉽다. 중앙은행 입장에서는 악몽 같은 시나리오다. 인플레이션 기대 심리가 흔들리면\n볼커처럼 시장을 과도하게 긴축해\n꽤 고통스러운 경기 침체를 유발해야만 그 기대를 다시 잡을 수 있기 때문이다. 바로 그것이 1970년대의 고전적인 교훈이다.\n2022년에는 기대 심리가 흔들리지 않았다. 하지만 그것이 중앙은행가들이 가장 두려워하는 시나리오다.\nQ. 2022년이 얼마나 참고가 될까? 두 상황의 공통점과 차이점은 무엇인가?\nA. 가장 큰 공통점은 공황 심리다. 하지만 실질적인 기본 여건은 상당히 다르다. 2022년으로 들어갈 때 석유 시장은 매우 빡빡한 상태였다. 석유수출국기구\nOPEC\n은 코로나19로 수요가 폭락한 2020년에 시장 균형을 위해 대규모 감산을 단행했는데, 당시 상황에서 옳은 결정이었다고 본다. 극심한 채찍 효과를 막아준 선택이다. 어쨌든 수요와 세계 경제가 예상보다 훨씬 빠르게 회복되는 동안 공급이 따라가지 못했다. 재고는 고갈되고 있었고 러시아의 우크라이나 침공 이전부터 이미 가격은 세 자릿수를 향해 치닫고 있었다.\n그리고 러시아가 침공했다. 가장 큰 우려는 국제에너지기구(IEA)의 4월 보고서였는데 서방의 수입 금지와 제재 조치가 맞물려 러시아 공급량이 하루 300만 배럴 감소할 것이라는 내용이었다. 당시 정말 엄청난 공급 손실이라고 생각했다. 그런데 결국 실제 손실은 100만 배럴 수준이었고 그마저도 곧 회복됐다.\n지금은 상황이 다르다. 이번 사태 직전까지 시장은 상당히 여유 있는 상태였다. 하루 200만~300만 배럴의 공급 과잉이 예상되는 상황이었다. OPEC도 증산을 단행했고 세계 수요는 양호하지만 눈부신 수준은 아니었다. 전반적으로 재고가 쌓이면서 가격을 끌어내릴 것처럼 보였다. 오히려 작년에 가격이 더 떨어지지 않은 것은 백악관이 베네수엘라, 이란, 러시아에 강력한 제재 정책을 펼쳤기 때문이다.\n지금 일어나고 있는 일은 러시아에서 하루 300만 배럴을 잃을 것이라는 우려와 호르무즈 해협 봉쇄로 실제 하루 2000만 배럴이 빠져나가는 현실의 차이다. 공급 손실이 무려 7배 규모다. 게다가 러시아 침공 때는 300만 배럴을 실제로 잃지 않았다. 하지만 지금은 하루 2000만 배럴이 실제로 시장에서 사라진 상태다.\nQ. 그러니까 이번 위기는 차원이 완전히 다른 문제라는 말인가.\nA. 맞다. 지금 많은 사람들이 이렇게 말한다. "러시아 때도 잘 넘겼잖아. 결국 별것 아니었어. 시스템이 얼마나 유연하게 적응하는지 보여줬잖아." 시장에 일종의 근거 없는 낙관론이 퍼져 있다. "이번에도 어떻게든 해결되겠지." 물론 시스템도 우회로를 찾으려 하고 있다.\n사우디아라비아의 동서 파이프라인\n은 걸프에서 홍해로 하루 최대 500만 배럴을 이송할 수 있다고 하는데 아직 실제로 검증된 수치는 아니다. 그래도 현재로선 최대 단일 대안이다. 다만 몇 년 전처럼\n후티 반군이 다시 문제가 될 수 있다\n. 러시아와 베네수엘라의 제재 우회 물량도 여기저기 떠돌고 있다.\n현재 이 전쟁에서 가장 큰 수혜를 보는 나라는 러시아다. 트럼프 백악관은 러시아 제재를 상당히 강화하는 데 성공했고 모스크바에는 점점 불리한 상황이 조성되고 있었다. 8개월에 걸쳐 이뤄낸 성과인데 이 전쟁 단 2주 만에 그것이 모두 허사가 됐다. 인도는 러시아산 원유를 사들이려 혈안이 됐다. 모두가 러시아 원유를 찾고 있다. 심지어 동유럽도 브뤼셀에 "EU의 러시아 수입 제재를 완화할 수 없냐"고\n목소리를 높이고 있다\n. 과거의 대형 파이프라인이 지금 같은 세계적 석유 충격에서는 정말 요긴하기 때문이다.\n국제에너지기구(IEA)는 약 120일에 걸쳐 전략 비축유 4억 배럴을 방출하겠다고\n발표\n했다. 하루 약 330만 배럴이 시스템으로 환류되는 셈인데, 2022년이었다면 그 자체로 엄청난 규모겠지만 지금 우리가 직면한 손실에 비하면 여전히 극히 일부에 불과하다.\nQ. 중간 소득 국가들은 어떤 영향을 받을까? 그리고 세계 경제에는 어떻게 작용할까? 유럽이나 미국과 달리 인도나 베트남 같은 나라들은 고유가를 버텨내는 방식이 다를 텐데.\nA. 매우 중요한 지적이다. 시장이 어떻게 해결책을 찾을 것이냐를 논하는 동안 결국 누군가는 연료 없이 살아야 한다는 인간적인 현실을 마주해야 한다. 공급이 수요를 감당하지 못하면 누군가는 소비를 줄여야 한다. 문제는 그 누군가가 누구냐다.\n시장의 논리는 단순하다. 가격에 가장 민감한 사람들, 다시 말해 지구에서 가장 가난한 사람들이 수요를 줄여야 하는 쪽이 된다. 북미나 유럽, 부유한 아시아에 사는 우리에게는 심각한 가격 충격이 될 것이다. 경기 침체 우려도 있고 불만도 쏟아지며 정치적으로도 매우 부담스러운 상황이 될 것이다. 하지만 결국 우리는 실질적인 물자 부족 사태는 겪지 않을 가능성이 크다. 높은 가격을 치르면서라도 수입을 유지할 수 있는 능력이 있기 때문이다.\n반면 개발도상국과 글로벌 사우스에서는 그 경제 안에 높은 가격을 감당할 수 있는 사람들이 일부 있다 해도 평균적인 소비자는 그럴 수 없다. 높은 가격으로 수입을 유치할 능력이 없기 때문에 실제로 물리적인 부족을 경험하게 될 가능성이 크다.\n2022년 유럽의 천연가스 가격 위기 때도 이런 사례가 있었다. 파키스탄으로 향하던 LNG 운반선이\n계약을 파기하고 유럽으로 방향을 돌린 사건\n이다. 계약 위반 벌금이 있었지만, 파키스탄과 유럽의 가격 차이에서 오는 차익에 비하면 아무것도 아니었다. 시장의 논리는 가장 높은 가격을 쳐주는 곳으로 물량을 보낸다.\n어떤 이들은 그게 시장의 작동 원리라고 말할 것이다. 하지만 그 이면의 현실도 있다. 파키스탄에는 가스가 없었다. 발전, 난방, 그 밖의 모든 용도에 지장이 생겼다. 결코 좋은 일이 아니다.\n앞으로도 마찬가지다. 가장 높은 가격을 낼 수 있는 나라가 연료를 가져간다. 세계 교역이 자유롭게 유지되는 한 부유한 나라는 매우 비싼 값을 치르더라도 석유를 확보할 것이다. 반면 글로벌 사우스는 없는 채로 버텨야 할 것이다.\nQ. 기업들이 다가오는 충격에서 스스로를 보호하기 위해 할 수 있는 일이 있을까? 아니면 그냥 시장과 지정학에 맡기는 수밖에 없을까?\nA. 연료를 소비하는 기업 입장에서 보면 시장은 아직 이 상황이 장기화될 것이라는 전망을 가격에 충분히 반영하지 않고 있다. 미래 시점의 물량은 현재 현물 가격보다 훨씬 저렴하게 확보할 수 있다. 지금 당장의 수요가 현물 공급에 집중돼 있기 때문이다. 물론 나 역시 이 상황이 단기에 끝날 것이라고 잘못 전망했다.\n이 상황이 계속된다면 여건은 더 나빠지고 가격은 더 오를 것이다. 지금처럼 유리한 가격에 헤지할 기회가 사라지게 된다. 지금이 기회다. 문제는 양방향 리스크다. 많은 시장 참가자들이 움직이지 못하는 이유이기도 하다. 지난 월요일 브렌트유는 장중 배럴당 120달러에 육박했다가 85달러 수준까지 내려앉았다.\n하루 35달러 차이\n다. 이런 변동성 속에서 헤지를 시도하면 상승 리스크를 일부 방어할 수 있지만, 동시에 막대한 손실 리스크를 떠안을 수도 있다. 내일 백악관이 전쟁 종결을 선언하고 통항이 재개된다면 가격이 순식간에 폭락할 수도 있다.\n지금은 극도로 불확실한 때다. 결국 이 모든 것은 사실상 한 사람의 정책 결정에 달려 있어 보인다. 그러나 트럼프가 내일 전쟁을 끝내기로 해도 이스라엘은 어떻게 할 것이며 이란은 어떻게 반응할까?\n내가 좋아하는 말이 있다. "리스크는 세계 시장의 톱니바퀴에 윤활유가 된다. 불확실성은 그 톱니바퀴를 멈춰 세운다." 지금이 딱 그 상황이다. 사람들이 "언제 끝날지 모르겠다"며 멈춰버렸다. 좋은 예가 하나 있다. 걸프에 갇힌 선박들은 천문학적인 전쟁 보험료를 내고 빠져나가거나, 하루이틀 기다리면 사실상 공짜로 나갈 수 있는 상황이다. 결국 모든 것이 시장이 이 상황의 지속 기간을 얼마로 보느냐에 달려 있다.\n시장이 이것을 단기 에피소드로 볼수록 실제로 단기에 끝나지 않을 경우 나머지 시장과 경제가 대비할 여지는 줄어든다. 지금 우리가 빠진 함정이다.\n도저히 지속 불가능한 상황이다. 시장은 물리적 현실이 모두의 손을 강제로 움직일 때까지 버티며 기다리고 있다. 아시아에서 하루 1000만 배럴씩 재고가 빠져나가는 상황이 오면 백악관의 어떤 말도 그것을 막을 수 없다. 결국 시장이 지금 일어나고 있는 일의 물리적 현실을 직시해야만 비로소 상황이 움직일 것이다.\n원문 |\nhttps://hbr.org/2026/03/the-oil-shock-is-here-and-were-just-beginning-to-feel-it\n토마스 스택폴\n(Thomas Stackpole) 은 하버드비즈니스리뷰의 선임 편집자다.'

#### df_hbr 데이터 결측치제거, 데이터범위 맞추기 (2023~2026년)

In [ ]:
# published_date 결측치 제거 후 복사본 생성
df_hbr_copy = df_hbr.dropna(subset=["published_date"]).copy()

# published_date 컬럼을 문자열로 변환하고 앞뒤 공백 제거
df_hbr_copy["published_date"] = df_hbr_copy["published_date"].astype(str).str.strip()

# 2023, 2024, 2025, 2026으로 시작하는 날짜만 필터링
df_hbr_date = df_hbr_copy[
    df_hbr_copy["published_date"].str.startswith(("2023.", "2024.", "2025.", "2026."))
].copy()

# 결과 확인
print("원본 데이터 개수:", len(df_hbr))
print("published_date 결측치 제거 후 데이터 개수:", len(df_hbr_copy))
print("2023~2026 데이터 개수:", len(df_hbr_date))

# 필터링된 날짜 컬럼 일부 확인
df_hbr_date["published_date"].head()

원본 데이터 개수: 2062
published_date 결측치 제거 후 데이터 개수: 2034
2023~2026 데이터 개수: 1267

0    2026. 5. 14.
1    2026. 5. 12.
2     2026. 5. 8.
3     2026. 5. 7.
4     2026. 5-6월호
Name: published_date, dtype: object

In [ ]:
df_hbr_date

,title,content,url,category,published_date,source,summary,clean_content
0,AI ROI를 좌우하는 7가지 요인,기업이 AI에 막대한 자금을 투입하고 있다. 미국 기업들은 2025년 한 해에만 생...,https://www.hbrkorea.com/article/view/atype/di...,전략,2026. 5. 14.,HBR Korea,기업이 AI에 막대한 자금을 투입하고 있다. 미국 기업들은 2025년 한 해에만 생...,기업이 AI에 막대한 자금을 투입하고 있다. 미국 기업들은 2025년 한 해에만 생...
1,AI 전환을 저해하는 ‘라스트 마일’ 문제,"경영진은 AI 기반의 전환이 가져다 줄 전망에 점점 더 매료되고 있으며, 이에 맞춰...",https://www.hbrkorea.com/article/view/atype/di...,전략,2026. 5. 12.,HBR Korea,"경영진은 AI 기반의 전환이 가져다 줄 전망에 점점 더 매료되고 있으며, 이에 맞춰...","경영진은 AI 기반의 전환이 가져다 줄 전망에 점점 더 매료되고 있으며, 이에 맞춰..."
2,호르무스 봉쇄의 진짜 충격은 이제부터…,미국-이스라엘의 대이란 전쟁이 계속되는 가운데 이 전쟁이 세계 경제에 미칠 영향은 ...,https://www.hbrkorea.com/article/view/atype/di...,전략,2026. 5. 8.,HBR Korea,미국-이스라엘의 대이란 전쟁이 계속되는 가운데 이 전쟁이 세계 경제에 미칠 영향은 ...,미국-이스라엘의 대이란 전쟁이 계속되는 가운데 이 전쟁이 세계 경제에 미칠 영향은 ...
3,양 극단만 살아남는 새로운 경쟁 법칙,인도의 이커머스 기업 던조\nDunzo\n는\n60분 이내\n배송을 내세우며 201...,https://www.hbrkorea.com/article/view/atype/di...,전략,2026. 5. 7.,HBR Korea,주요 도시로 서비스를 확장했고 2021년 8월에는 퀵커머스,인도의 이커머스 기업 던조 Dunzo 는 60분 이내 배송을 내세우며 2014년 출...
4,세라젬의 혁신 성장,세라젬의 혁신 성장\n의료기기 제조사에서 AI 웰니스 홈 플랫폼으로\n1998년 외...,https://www.hbrkorea.com/article/view/atype/ma...,전략,2026. 5-6월호,HBR Korea,"1998년 외환위기로 창업 환경이 최악이던 해, 이환성 세라젬 회장은 전 재산을 털...",세라젬의 혁신 성장 의료기기 제조사에서 AI 웰니스 홈 플랫폼으로 1998년 외환위...
...,...,...,...,...,...,...,...,...
2011,"바이탈, 지속가능한 포장 시스템을 만들다",전통적인 음식 포장과 배송은 심각한\n지속가능성 문제\n에 직면해 있다. 소비자 음...,https://www.hbrkorea.com/article/view/atype/di...,지속가능성,2023. 2. 2.,HBR Korea,"에 직면해 있다. 소비자 음료 포장은 도시 고체 폐기물의 최대 48%, 해양 쓰레기...",전통적인 음식 포장과 배송은 심각한 지속가능성 문제 에 직면해 있다. 소비자 음료 ...
2012,탄소중립 달성을 위한 '4A' 가이드,요즘 고객은 친환경적인 제품과 서비스를 요구한다. 투자자는 다음에 올 큰 기후 대응...,https://www.hbrkorea.com/article/view/atype/di...,지속가능성,2023. 2. 1.,HBR Korea,요즘 고객은 친환경적인 제품과 서비스를 요구한다. 투자자는 다음에 올 큰 기후 대응...,요즘 고객은 친환경적인 제품과 서비스를 요구한다. 투자자는 다음에 올 큰 기후 대응...
2013,수자원 위험에 대비하라,기업이 위험을 예측할 때 ‘물 부족’ 이슈까지 고려하기는 쉽지 않다. 역사적으로 보...,https://www.hbrkorea.com/article/view/atype/di...,지속가능성,2023. 1. 25.,HBR Korea,기업이 위험을 예측할 때 ‘물 부족’ 이슈까지 고려하기는 쉽지 않다. 역사적으로 보...,기업이 위험을 예측할 때 ‘물 부족’ 이슈까지 고려하기는 쉽지 않다. 역사적으로 보...
2014,화석연료 자산의 투자회수가 어려운 이유,‘화석연료를 사용하지 않겠다’는 약속은 꽤 심오하고 기후 친화적 선언으로 보이기 쉽...,https://www.hbrkorea.com/article/view/atype/di...,지속가능성,2023. 1. 19.,HBR Korea,‘화석연료를 사용하지 않겠다’는 약속은 꽤 심오하고 기후 친화적 선언으로 보이기 쉽...,‘화석연료를 사용하지 않겠다’는 약속은 꽤 심오하고 기후 친화적 선언으로 보이기 쉽...
2015,기후 대응을 위한 프레임워크,허리케인 이안에 이은 미국 플로리다의 최근 피해 상황을 보면 마음이 아프고 무겁다....,https://www.hbrkorea.com/article/view/atype/di...,지속가능성,2023. 1. 3.,HBR Korea,허리케인 이안에 이은 미국 플로리다의 최근 피해 상황을 보면 마음이 아프고 무겁다....,허리케인 이안에 이은 미국 플로리다의 최근 피해 상황을 보면 마음이 아프고 무겁다....

## 노이즈 데이터 제거

In [ ]:
import re
import pandas as pd


def clean_content(text):
    # content 값이 비어 있거나 NaN인 경우 빈 문자열로 처리
    if pd.isna(text):
        return ""

    # 숫자, NaN 등이 섞여 있을 가능성을 대비해 문자열로 변환
    text = str(text)

    # 원문 | 이후의 푸터 영역 전체 제거
    # 예: 원문 | https://hbr.org/... 이후 URL, 저자소개, 에디팅 정보 제거
    text = re.sub(
        r"(?m)^\s*원문\s*\|[\s\S]*$",
        " ",
        text
    )

    # 이메일 주소 제거
    # 예: abc@gmail.com, reporter@news.co.kr
    text = re.sub(
        r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",
        " ",
        text
    )

    # URL 제거
    # 예: http://example.com, https://news.com/article
    text = re.sub(
        r"http[s]?://\S+|www\.\S+",
        " ",
        text
    )

    # 실제 줄바꿈, 엔터, 탭 문자 제거
    # 예: \n최근 설문조사\n → 최근 설문조사
    text = re.sub(r"[\n\r\t]", " ", text)

    # 문자열 형태로 저장된 줄바꿈 문자 제거
    # 예: "\\n최근 설문조사\\n" → 최근 설문조사
    text = text.replace("\\n", " ")

    # 이스케이프된 따옴표 제거
    # 예: \'벤처·스타트업 근로시간 제도개편 간담회\'
    # 결과: 벤처·스타트업 근로시간 제도개편 간담회
    text = re.sub(r"\\['\"]", " ", text)

    # 본문에 남아 있는 \ 기호 제거
    # 예: \, \\, \\\ 등 연속된 \ 기호를 공백으로 변경
    text = re.sub(r"\\+", " ", text)

    # 일반 따옴표 제거는 제외
    # 기존 코드:
    # text = re.sub(r"[\"']", " ", text)

    # <내용> 형태 제거
    # 예: <저작권자>, <사진>, <뉴스본문> 등 꺾쇠괄호와 내부 내용 전체 제거
    text = re.sub(r"<[^>]*>", " ", text)

    # 재판매 및 DB 금지 문구 제거
    text = re.sub(
        r"\*?\s*재판매\s*및\s*DB\s*금지",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 대괄호로 묶인 출처/지역/언론사/광고 정보 제거
    text = re.sub(r"\[[^\]]*\]", " ", text)

    # 소괄호로 묶인 사진 설명, 출처, 부가 설명 제거
    text = re.sub(r"\([^)]*\)", " ", text)

    # 기사 본문에 포함된 날짜 형식 제거
    # 예: 2023.01.31. / 2023.1.31
    text = re.sub(r"\d{4}\.\d{1,2}\.\d{1,2}\.?", " ", text)

    # 한글 이름 + 기자 표현 제거
    # 예: 홍길동 기자, 김철수기자
    text = re.sub(r"[가-힣]{2,4}\s*기자", " ", text)

    # 기자 = 형태 제거
    # 예: 기자=, 기자 =
    text = re.sub(r"기자\s*=", " ", text)

    # 저작권, 무단전재, 재배포 금지, 제보 문구 제거
    text = re.sub(
        r"(무단\s*전재|재배포\s*금지|ⓒ|Copyright|제보를 기다립니다)",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 불필요한 특수기호 제거
    # 예: ▲, ▶, *, =, … 기호 제거
    text = re.sub(r"[▲▶*=…]", " ", text)

    # 여러 개의 공백을 하나의 공백으로 정리
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# content 컬럼을 전처리한 뒤 clean_content 컬럼에 저장
df_hbr_date["clean_content"] = df_hbr_date["content"].apply(clean_content)

# 전처리 전 content와 전처리 후 clean_content 비교 확인
df_hbr_date[["content", "clean_content"]].head()

,content,clean_content
0,기업이 AI에 막대한 자금을 투입하고 있다. 미국 기업들은 2025년 한 해에만 생...,기업이 AI에 막대한 자금을 투입하고 있다. 미국 기업들은 2025년 한 해에만 생...
1,"경영진은 AI 기반의 전환이 가져다 줄 전망에 점점 더 매료되고 있으며, 이에 맞춰...","경영진은 AI 기반의 전환이 가져다 줄 전망에 점점 더 매료되고 있으며, 이에 맞춰..."
2,미국-이스라엘의 대이란 전쟁이 계속되는 가운데 이 전쟁이 세계 경제에 미칠 영향은 ...,미국-이스라엘의 대이란 전쟁이 계속되는 가운데 이 전쟁이 세계 경제에 미칠 영향은 ...
3,인도의 이커머스 기업 던조\nDunzo\n는\n60분 이내\n배송을 내세우며 201...,인도의 이커머스 기업 던조 Dunzo 는 60분 이내 배송을 내세우며 2014년 출...
4,세라젬의 혁신 성장\n의료기기 제조사에서 AI 웰니스 홈 플랫폼으로\n1998년 외...,세라젬의 혁신 성장 의료기기 제조사에서 AI 웰니스 홈 플랫폼으로 1998년 외환위...

In [ ]:
df_hbr_date['clean_content'][0]

'기업이 AI에 막대한 자금을 투입하고 있다. 미국 기업들은 2025년 한 해에만 생성형 AI에 370억 달러를 지출한 것으로 추정된다 . 최고경영진과 이사회는 점점 더 AI 투자 수익률에 대해 의문을 갖기 시작했으며, 적절한 답변을 제시하지 못하는 리더들에게는 실질적인 압박이 가해질 수 있는 상황이다. 최근 설문조사 에서 전 세계 최고정보책임자 의 71%는 2년 이내에 AI의 가치를 입증하지 못할 경우 관련 예산이 동결되거나 삭감될 것이라고 응답했다. 필자들은 기업이 이러한 과제에서 어떤 성과를 거두고 있는지, 가까운 미래에 어떤 방향으로 나아갈 것으로 예상하는지에 대해 자세히 살펴보기로 했다. 이에 스케일드애자일 Scaled Agile AI 교육 사업부의 후원으로2025년 말부터 2026년 초에 걸쳐 기업들이 AI로부터 얻는 가치에 대한 인식과 그 실현 방식에 대한 연구를 수행했다. 이 연구에는 대기업의 기술, 데이터, AI 분야 리더 12명과의 인터뷰, 소속 조직의 AI 이니셔티브에 대해 깊이 이해하고 있는 전 세계 고위 경영진 1006명을 대상으로 한 설문조사가 포함됐다. 연구 결과는 놀라울 정도로 긍정적이었다. 응답자의 45%는 AI로부터 ‘상당한 가치’를 창출하고 있다고 답했고, 또 다른 45%는 ‘중간 수준의 가치’를 창출하고 있다고 답했다.?반면, ‘소규모 가치’를 창출하고 있다고 답한 응답자는 9%에 불과했으며, ‘가치가 전혀 없다’고 답한 응답자는 사실상 제로에 가까운 0.2%였다. 이처럼 비교적 높은 수준의 성과에 대한 인식은 생성형 AI에서 얻은 성과에 초점을 맞춘 연구에서 훨씬 낮은 투자 수익률을 보고한 것과 반대되는 결과다. 하지만 기업이 어떻게 가치를 창출하는지가 진정 흥미로운 점이다. 필자들은 AI로부터 경제적 가치를 이끌어낼 수 있는 7가지 요인을 확인했다. 더 나아가 이러한 가치 창출 요인 중 일부는 서로 결합해 AI 가치 창출 수준을 높이는 ‘경제적 성숙도 모델’로 발전할 수 있다. 높은 AI 가치를 창출하는 7가지 요인 먼저, 가치를 창출하지 못하는 요소부터 살펴보자. 예를 들어, 인력 감축은 아직 의미 있는 가치 창출 요인이 아니다. 이전 아티클 에서 밝힌 바와 같이, 실제로 활용 중인 AI 기능에 의해 인력 감축이나 채용 축소가 경우는 2%에 불과하다. 나머지는 AI에 대한 기대 효과나 다른 이유로 이뤄진 감원을 AI 성과처럼 포장하는 이른바 ‘AI 워싱 AI washing ’에 해당한다. 생성형 AI 역시 아직까지 기업에 높은 수준의 가치를 제공하지는 못하고 있다. 최고 AI 책임자 또는 최고 데이터 및 AI 책임자 직책을 신설하는 것만으로는 가치를 창출하지 못한다. 설문 응답자와 기업의 기술 리더들에 따르면, 7가지 요소를 종합해 볼 때 데이터는 한 방향을 가리키고 있다. 가장 정교한 기술을 보유한 조직이 꼭 AI로부터 최대의 성과를 얻는 것은 아니라는 점이다 이들을 구분 짓는 요소는 더욱 근본적인 데 있다. 즉, 리더들이 조직에 있어 가치가 무엇을 의미하며 얼마나 명확하게 정의하는지, 그 가치를 실현할 책임을 누구에게 부여하는지, 성과 측정을 단순한 보고 절차가 아닌 경영 관리의 핵심 수단으로 얼마나 진지하게 다루는지 하는 점이다. 고부가가치를 창출하는 기업에서 효과가 있는 것으로 보이는 요소들은 다음과 같다. 1. 달성하고자 하는 가치의 유형을 명확히 하라 설문 응답자의 대다수는 AI로부터 가치를 얻고 있다고 답했다. 그러나 그들이 정의하는 가치의 의미는 상당히 다양하다. 예를 들어, 응답자의 14%는 AI로부터 상당한 가치를 얻고 있다고 답했지만 해당 기술에 대한 투자 수익 은 미미하다고 보고했다. 반대로, 9%는 가치는 중간 수준이지만 ROI는 상당하다고 보고했다. 이러한 차이는 무엇을 의미하는가? 핵심은 간단하다. 가치는 결국 보는 사람의 관점에 따라 달라진다. 여기에서 ‘가치’는 “AI가 우리가 기대한 대로 작동하고 있다”는 의미로 이해해야 한다. 일부 조직은 단기적인 ROI를 추구하는 반면, 다른 조직은 장기적인 전환을 추구한다. 캐피털원 Capital One 의 부사장 겸 엔터프라이즈 AI, 데이터 및 직원 기술 부문 책임자인 프렘 나타라잔 Prem Natarajan 은 은행이 단기적인 수익 추구에만 집중하지 않는 이유를 다음과 같이 설명한다. 단기적 가치에만 집중하는 것이야말로 많은 기업이 장기적 가치를 창출하는 기술 혁신을 결코 이루지 못하는 이유다. 현대적인 기술 스택을 기반으로 자체 데이터에 깊이 투자한 기업만이 AI를 중심에 두고 혁신을 이룰 수 있는 위치에 서게 될 것이다. 반면, 다른 조직들은 AI 투자에 대한 보다 즉각적인 수익에 초점을 맞출 수도 있다. 그러나 어떤 경우든 리더들은 어떤 가치를 어떤 이유로 달성하려는지 명확히 해야 한다. 2. 즉각적인 성과가 나오지 않더라도 제품과 프로세스 모두에서 가치를 추구하라 대부분의 조직은 AI를 통한 가치 창출을 내부 프로세스 개선에 집중시키는 경향이 있다. 그러나 우리가 인터뷰한 임원 중 몇몇은 고객 대상 서비스에서의 AI 활용에도 동등하거나 더 큰 비중을 두고 있었다. 그러한 예로 생명과학, 헬스케어, 전자 분야를 아우르는 독일 다름슈타트 소재 머크 KGaA Merck KGaA 의 최고 과학기술 책임자 로라 마츠 Laura Matz 를 들 수 있다. 그녀는 이 다각화된 기업이 프로세스 중심 AI와 제품 중심 AI 이니셔티브를 동시에 추진하고 있다고 설명했다. AI를 접목한 대부분의 제품이나 신규 사업은 비교적 신생 단계이며, 시범 운영 중이므로 규모가 확대되기 전까지는 그 가치를 평가하기 어렵다. 새로운 AI 기반 서비스에는 새로운 생태계, 비즈니스 모델, 혹은 기술 개발이 필요하다. 그러나 350년 이상의 역사를 보유한 머크 KGaA는 혁신에 대해 장기적인 관점을 갖고 있다. 프랑스의 다국적 에너지 기술 기업 슈나이더 일렉트릭 Schneider Electric 의 최고 AI 책임자 필리프 랑바흐 Philippe Rambach 는 의도적으로 이중적인 전략을 취하고 있다고 설명했다. 내부 AI 활용은 즉각적인 재무적 성과를 창출해 직원들이 더 빠르고 효율적으로 일할 수 있도록 지원하는 동시에 고객 지원도 강화한다. 슈나이더 일렉트릭의 대외용 AI는 변화하는 시장에서 시장 점유율을 확보하는 데 초점을 맞춘 장기적인 전략적 접근이다. 각각은 성과 측정 방식과 가치를 실현하는 시간축이 서로 다르다. AI는 기존의 기업 가치를 방어하는 수단으로도 이해될 수 있다. 미국 올림푸스 Olympus Corporation of Americas 사장 줄리앙 소바냐르그 Julien Sauvagnargues 는 자사의 의료 기술 포트폴리오에 내시경이 포함돼 있으며, AI 기반 보조 의료기기 소프트웨어와 함께 사용돼 암이 될 가능성이 있는 용종 polyps 을 식별할 수 있다고 설명했다. 그는 기업이 AI 솔루션을 단순히 새로운 가치를 창출하는 수단이 아니라 시장 점유율을 방어하는 수단으로 인식해야 한다고 강조했다. "AI는 시장에서 매력적인 요소입니다. 우리 제품에 AI가 없다면 시장 점유율을 잃게 될 것입니다. 우리는 AI 도입 비용과 도입하지 않을 경우 발생하는 비용이 얼마나 큰지 잘 알고 있습니다." 올림푸스는 개인 생산성 향상을 위해서도 AI를 활용하고 있지만 아직 생산성 향상 효과를 정량화하지는 않고 있다. 3. AI 도구 상자를 폭넓게 활용하라 생성형 AI가 언론의 주목을 주도적으로 받고 있지만 대부분의 기업이 가장 가치 있다고 여기는 영역은 아니다. 설문 응답자 중 50%는 동적 dynamic 가격 책정이나 고객 타깃팅과 같은 분석형 AI에서 가장 큰 가치를 얻고 있다고 답했다. 그 다음으로는 자금세탁 방지 시스템, 보험 인수 심사, 의료 임상 의사결정 지원, 로보틱 프로세스 자동화 등에서 흔히 볼 수 있는 규칙 기반 AI가 근소한 차이로 2위를 차지했다. 이러한 도구들이 가장 큰 가치를 창출한다고 응답한 비중은 40%였다. 반면, 생성형 AI를 선택한 응답자는 9%에 불과했고, 에이전틱 AI를 선택한 비율은 2%에 그쳤다. 다만 이 기술들이 본격적으로 도입된 것은 불과 몇 년 밖에 되지 않았다는 점을 고려할 필요가 있다. 그럼에도 불구하고 에이전틱 AI 의 도입은 AI 가치 창출의 지표가 된다. 이를 도입한 기업은 그렇지 않은 기업보다 AI 전반에서 상당한 가치를 창출한다고 응답할 가능성이 22% 더 높으며, 보다 성숙한 경제적 가치 관행을 활용할 가능성도 높다. 4. 가치 창출을 위한 프레임워크나 방법론을 도입하라 자체 개발된 것이든 경영 이론에서 차용한 것이든 AI를 아이디어 단계에서 생산 단계, 측정 가능한 가치 단계로 전환하기 위해서는 체계적인 접근 방식이 꼭 필요하다. 예를 들어, 미국의 은행 지주 회사 앨리 파이낸셜 Ally Financial 은 사용 사례 탐색부터 책임 있는 운영 배포에 이르기까지 사업 부문을 안내하는 자체 ‘AI 플레이북’을 운영하고 있다. 또 다른 사례로, 한 전력 회사는 R&D 분야에서 주로 사용되는 ‘스테이지 게이트 stage gate ’ 접근 방식을 활용해 동일한 과정을 관리하고 있다. 그러나 인터뷰 대상자들 사이에서 가장 일반적인 접근 방식은 디지털 제품 중심 접근법이다. 이는 내부 및 외부 AI 서비스를 기획부터 구현, 지속적인 운영에 이르기까지 하나의 제품으로 관리하는 방식이다. 미국 중고차 판매업체 카맥스 CarMax 의 부사장 겸 최고정보기술책임자 인 샤민 모하메드 Shamin Mohamed 는 가치 창출의 가장 중요한 요인으로 ‘제품 중심 접근 방식’을 꼽았다. 그는 “이 접근 방식은 기대 효과를 제안하고, 이를 지속적으로 검토하며, 비즈니스를 변화시키고, 이해관계자들이 달성된 가치에 대해 책임을 지도록 만드는 구조를 제공합니다”라고 말했다. 모든 가치 프레임워크에는 AI 활용을 위한 데이터 준비 방법도 반드시 포함돼야 한다. 응답자의 55%가 데이터 준비 부족을 가치 창출의 걸림돌로 꼽았는데, 이는 다른 설문조사 결과와도 일치한다. 5. 가치 실현 및 검증 과정에 CFO와 재무 부서를 참여시킨다 대부분의 조직은 AI 가치에 대한 책임을 최고 데이터/분석/AI 책임자 나 개별 사업부 임원 에게 부여한다. CFO에게 책임을 부여하는 경우는 단 2%에 불과하다. 그러나CFO가 AI 가치 창출을 책임질 경우, 응답자의 76%가 “상당한” 가치를 달성했다고 보고했다. 이는 CIO나 CTO가 책임질 때의 53%, 사업부 임원 중심에서 32%에 불과한 수치와 대비된다. 재무 부서는 다른 조직에서는 종종 부족하기 쉬운 엄밀성, 신뢰성, 그리고 조직적 권한을 제공한다. 인터뷰에 응한 여러 기업에서는 재무 조직이 기술 임원들과 협력해 AI로 창출된 가치를 검증하고 있다. 싱가포르에 본사를 둔 DBS 은행의 AI 총괄자인 니미시 판치마티아 Nimish Panchmatia 는 그들의 접근 방식을 다음과 같이 설명했다. 2021년부터 우리 은행은 연차보고서에서 데이터 분석과 AI가 창출한 경제적 가치를 공개하고 있다. A/B 테스트 결과를 추적하고, 그 차이를 경제적 가치로 정량화한다. 각 사업부 CFO가 해당 수치를 검증한 뒤 이를 그룹 차원의 총 가치로 통합한다. 6. 사용자와 경영진 모두를 대상으로 AI 교육을 실시하라 AI 도입에는 이중 구조의 과제가 존재한다. 58%의 조직은 직원들에게 AI 생산성 및 도구 활용에 대한 교육을 실시하지 않았으며, 29%는 경영진이 AI 가치 창출을 주도할 만큼의 이해가 부족하다고 인정한다. 직원 역량 강화와 경영진의 AI 활용 능력 향상에 모두 투자하는 조직은 가치 실현 측면에서 23%포인트 높은 성과를 보인다. 중요한 점은 직원들의 저항이 장벽이 아니라는 것이다. AI 가치 실현의 걸림돌로 직원들의 저항을 꼽은 기업은 13%에 불과하다. 직원들은 AI를 거부하는 것이 아니라 효과적인 경영진의 리더십과 가치 프레임워크 부재, 미비한 데이터 등 다른 장벽이 제거되기를 기다리고 있다. 7. AI 경제적 가치 성숙도 모델을 활용하라 이러한 모델은 가치 달성 수준에 있어 유의미한 차이를 예측한다. 이 경제적 성숙도 모델은 세 가지 구성 요소를 기반으로 한다. 첫 번째는 AI 시스템을 실제 운영에 투입하는 것이다. 파일럿이나 실험은 학습에는 유용할 수 있으나 직접적인 경제적 가치를 창출하지는 못한다. 실제 운영 사례가 많을수록 좋다. 현재 파일럿 프로젝트는 하나 이상 있지만 실제 운영하는 사례는 없다고 응답한 비율은 6%에 불과했다. 반면, 58%는 하나 또는 몇 개의 실제 운영 사례를 보유하고 있다고 답했으며, 36%는 다양한 유형의 AI를 활용한 다수의 운영 사례를 보유하고 있다고 답했다. 성숙도 모델의 두 번째 구성 요소는 생산 환경에서의 AI 활용 사례의 가치를 평가하는 것이다. 이상적으로는 도입 전과 후 모두에서 가치를 평가해야 한다. 본 설문조사에서 응답자의 거의 과반수가 도입 전후의 가치를 평가하고 있지만 이는 일부 활용 사례에 국한돼 있다. 모든 활용 사례에 대해 이를 수행하는 기업은 11%에 불과하다. 반면 32%의 기업은 도입 전 가치만 평가하고 있으며, 9%는 생산 환경에서 아직 활용 사례가 충분하지 않아 가치 평가 자체를 하지 않고 있다. 성숙도 모델의 세 번째 구성 요소는 조직 전반에 걸쳐 창출된 가치를 집계하고, 비공식적으로라도 보고하는 것이다. 놀랍게도 대다수 의 조직이 AI 사용 사례의 가치를 집계한다고 보고했다. 마지막 구성 요소는 보다 공식적인 보고이며, 일부 기업은 이를 외부에도 공개하고 있다. AI 경제적 성숙도 모델 이러한 구성 요소들을 기반으로 필자들은 AI 투자가 어떻게 추가적인 경제적 가치를 창출할 수 있을지 예측하는 모델을 개발했다. 이 모델은 6단계로 구성되며, 각 단계는 AI 활용의 정교성과 예상 ROI 측면에서 점진적으로 상위 수준으로 발전한다. 필자들은 이를 도출하기 위해 설문 응답을 분석하고, 응답자들이 각 조직이 AI 도입 여정의 어느 단계에 있는지, 그리고 조직이 ‘상당한 가치’를 달성했는지 여부를 살펴봤다. 작동 방식은 다음과 같다. 0단계: 측정되지 않은 파일럿 단계 조직은 AI 실험을 수행하지만 그 성과를 측정하지 않는다. 이 단계에 속한 응답자 중 단 4%만이 “상당한 가치”를 창출했다고 답했다. 1단계: 평가 없는 운영 단계 이 단계에서 조직은 파일럿 단계를 넘어 AI를 실제 운영 환경에 적용한다. 즉, 실제 비즈니스 업무에 AI를 활용하고 있지만 그로 인한 비즈니스 영향에 대해서는 평가하지 않는다. 우리는 단순히 파일럿 단계를 넘어서는 것만으로도 ROI가 비약적으로 향상된다는 사실을 확인했다. 이 단계에서는 응답자의 18%가 AI 투자로부터 “상당한” 가치를 얻었다고 보고했다. 2단계: 도입 전 평가 단계 이 단계에서 조직은 AI 도입이 비즈니스에 미치는 영향을 보다 체계적인 방식으로 고려하지만 이는 프로세스의 초기 단계에만 국한된다. 즉, ROI 예측과 비즈니스 사례를 통해 AI 프로젝트의 타당성을 확보하지만 여전히 그 결과를 검증하지는 않는다. 이전 단계에 비해 “상당한” 가치를 얻고 있다고 응답한 비율이 20%로 소폭 증가하는 데 그치는 진전이다. 이는 모델 내 단계 전환 중 가장 낮은 수준의 성과 개선에 해당한다. 3단계: 도입 후 평가 단계 이 단계에서 조직은 도입 이후 AI 활용 사례를 개별적으로 측정한다. 이 과정은 가치 창출의 급격한 증가를 가져온다. 이 단계 응답자의 44%가 AI로부터 "상당한" 가치를 얻고 있다고 답했으며, 이는 2단계의 두 배 이상이다. 따라서 필자들은 이 지점을 AI 도입 여정에서의 첫 번째 주요 변곡점으로 규정했다. 하지만 기업들이 이 단계에서 정체되는 경향도 발견했다. 응답자들은 이 단계에서 평균 6년을 머무른다고 답했으며, 이는 일종의 병목으로 작용한다. 4단계: 연간 통합 평가 단계 이 단계에서는 조직이 매년 포트폴리오 전반에 걸쳐 AI 가치를 집계하고, 그 혜택을 조직 차원의 통합 가치로 환산한다. 그리고 그 결과를 사내에 비공식적으로 공유한다. 이를 통해 경영진은 AI 총 투자 비용 대비 총 가치를 비교할 수 있으며, 매출 및 이익의 증감도 대조해 볼 수 있다. 이처럼 보다 체계화된 프로세스는 가치 창출 수준을 한 단계 도약시킨다. 이 단계에서는 응답자의 58%가 AI로부터 “상당한” 가치를 창출했다고 보고했다. 5단계: 공식 보고 단계 마지막 단계에서 조직은 이사회, 투자자 또는 공공 시장에 AI로 창출된 가치를 보고한다. 이는 AI 가치 측정에 있어 높은 수준의 엄밀성과 책임성을 요구한다. 이 단계에서 가치 창출 수준은 다시 한번 급격히 상승한다. 응답자의 85%가 AI로부터 “상당한” 가치를 창출했다고 보고했으며, 이는 두 번째이자 가장 큰 변곡점이다. 일부 경영진은 외부 보고에 대해 신중한 입장을 보였다. 한 경영진은 강력한 AI 성과가 공개될 경우 애널리스트들이 회사에 배당금 증액을 압박할 수 있다는 우려를 제기했다. 그러나 인터뷰에 응한 경영진들은 일반적으로 책임 있는 방식으로 수행될 경우 공식적인 외부 보고가 AI 경제적 성숙도의 최고 단계를 의미한다고 평가했다. AI 가치를 실현하는 길은 대체로 기술적 과제가 아니라 경영적 과제다. 이제 모든 조직이 AI 기술을 접할 수 있지만 실질적이고 측정 가능한 경제적 성과를 창출하는 방식으로 이를 활용하는 곳은 일부에 불과하다. 이 아티클에서 제시한 7가지 요소와 특히 성숙도 모델은 그러한 조직으로 도약하기 위한 실질적인 실행 로드맵을 제시한다.'

## 불용어 사전 적용

In [ ]:
!pip install kiwipiepy
from kiwipiepy import Kiwi
import pandas as pd

# 형태소 분석기 초기화
kiwi = Kiwi()


# ============================================================
# HBR / DBR 아티클용 불용어 사전
# ============================================================
# 뉴스 기사용 불용어에서 언론사/기자/보도 표현은 줄이고,
# 아티클 구조상 자주 반복되는 표현을 추가한 버전
# ============================================================

STOPWORDS = {
    # ============================================================
    # 1. 일반 불용어
    # ============================================================
    "것", "수", "등", "및", "때", "중", "더", "또",
    "관련", "경우", "대상", "약", "정도", "부분",
    "내용", "방식", "방법", "수준", "결과", "사례",

    # ============================================================
    # 2. 조사·연결·전환 표현
    # ============================================================
    "위해", "통해", "대한", "또한", "한편",
    "따라", "이에", "다만", "특히", "반면",
    "예를", "그러나", "하지만", "그리고", "따라서",
    "즉", "먼저", "마지막", "다음",

    # ============================================================
    # 3. 시점 표현
    # ============================================================
    "이번", "지난", "올해", "내년", "최근", "현재", "향후",
    "오늘", "내일", "이날", "이후", "이전", "초기",
    "단기", "장기", "매년",

    # ============================================================
    # 4. 아티클 구조 관련 표현
    # ============================================================
    "아티클", "필자", "저자", "본문", "원문",
    "에디팅", "설문조사", "설문", "조사", "연구",
    "인터뷰", "응답자", "대상자", "질문", "답변",
    "응답", "비율", "퍼센트",

    # ============================================================
    # 5. 순서·단계 서술 표현
    # ============================================================
    "첫번째", "두번째", "세번째", "네번째", "다섯번째",
    "여섯번째", "일곱번째",
    "단계", "요소", "구성", "항목", "모델",

    # ============================================================
    # 6. 인물명 및 직책 관련 단어
    # ============================================================
    # 단, CFO, CIO, CTO 같은 직책 약어는 AI 투자 분석에서 의미가 있을 수 있어 유지
    "토머스", "대븐포트", "락스", "스리니바산",
    "김민수", "교수", "학과장", "방문", "연구원",
    "고문", "창립자", "공동", "최고운영책임자",

    # ============================================================
    # 7. 기관명·기업명
    # ============================================================
    # 기업명 자체가 키워드맵 목적에 불필요하면 제거
    "밥슨", "칼리지", "Babson", "College",
    "Metropoulos", "Institute", "Technology",
    "Entrepreneurship", "MIT", "Deloitte",
    "Return", "Institute", "Opera", "Solutions",
    "Scaled", "Agile", "Capital", "One",
    "Merck", "KGaA", "Schneider", "Electric",
    "Olympus", "Corporation", "Americas",
    "Ally", "Financial", "CarMax", "DBS",

    # ============================================================
    # 8. 아티클 서술 표현
    # ============================================================
    "말했다", "설명했다", "밝혔다", "전했다", "강조했다",
    "보고했다", "답했다", "응답했다", "꼽았다",
    "제시했다", "확인했다", "살펴봤다",
    "설명", "강조", "제시", "확인", "발견",
    "포함", "달성", "추구", "활용", "도입",
    "운영", "수행", "공개", "공유",

    # ============================================================
    # 9. 의미가 너무 넓은 추상어
    # ============================================================
    # 분석 결과에서 너무 많이 나오면 추가 제거 가능
    "기업", "조직", "리더", "경영진", "직원",
    "사용자", "고객", "업무", "경제", "재무"
}


# ============================================================
# 명사 추출 + 불용어 제거 함수
# ============================================================

def remove_stopwords_and_extract_nouns(text):
    # 값이 비어 있거나 NaN인 경우 빈 문자열 반환
    if pd.isna(text):
        return ""

    text = str(text)

    words = []

    # Kiwi 형태소 분석 수행
    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사
        # SL: 영어/외국어 표현, 예: AI, ROI, CFO
        if pos in ["NNG", "SL"]:

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            words.append(word)

    return " ".join(words)


# clean_content 컬럼을 기준으로 명사 추출 및 불용어 제거
df_hbr_date["analysis_content"] = df_hbr_date["clean_content"].apply(
    remove_stopwords_and_extract_nouns
)

# 결과 확인
df_hbr_date[["content", "clean_content", "analysis_content"]].head()

Requirement already satisfied: kiwipiepy in /usr/local/lib/python3.12/dist-packages (0.23.1)
Requirement already satisfied: kiwipiepy_model<0.24,>=0.23 in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (0.23.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (4.67.3)

,content,clean_content,analysis_content
0,기업이 AI에 막대한 자금을 투입하고 있다. 미국 기업들은 2025년 한 해에만 생...,기업이 AI에 막대한 자금을 투입하고 있다. 미국 기업들은 2025년 한 해에만 생...,AI 자금 투입 생성 AI 지출 추정 최고 이사회 AI 투자 수익 의문 시작 실질 ...
1,"경영진은 AI 기반의 전환이 가져다 줄 전망에 점점 더 매료되고 있으며, 이에 맞춰...","경영진은 AI 기반의 전환이 가져다 줄 전망에 점점 더 매료되고 있으며, 이에 맞춰...",AI 기반 전환 전망 매료 투자 확대 대부분 파일럿 프로젝트 추진 파일럿 Copil...
2,미국-이스라엘의 대이란 전쟁이 계속되는 가운데 이 전쟁이 세계 경제에 미칠 영향은 ...,미국-이스라엘의 대이란 전쟁이 계속되는 가운데 이 전쟁이 세계 경제에 미칠 영향은 ...,전쟁 계속 가운데 전쟁 세계 영향 핵심 석유 문제 자리 해협 봉쇄 세계 석유 공급량...
3,인도의 이커머스 기업 던조\nDunzo\n는\n60분 이내\n배송을 내세우며 201...,인도의 이커머스 기업 던조 Dunzo 는 60분 이내 배송을 내세우며 2014년 출...,커머스 Dunzo 이내 배송 출범 주요 도시 서비스 확장 커머스 quick comm...
4,세라젬의 혁신 성장\n의료기기 제조사에서 AI 웰니스 홈 플랫폼으로\n1998년 외...,세라젬의 혁신 성장 의료기기 제조사에서 AI 웰니스 홈 플랫폼으로 1998년 외환위...,혁신 성장 의료 기기 제조사 AI 웰니스 플랫폼 외환 위기 창업 환경 최악 회장 재...

In [ ]:
df_hbr_date["analysis_content"][20]

'비즈니스 정치 경계 결정 정부 일반 대중 경영자 정치 성향 갑론을박 블랙리스트 불매 운동 매출 감소 브랜드 이미지 타격 CEO 해고 비즈니스 정치 위험 감당 현실 오늘날 정치 환경 이해 전략 혁신 분야 저술가 연사 자문가 Martin Reeves 공저 L. Roger L. Martin Strategy in Hyperpolitical World 발표 환경 전략 수립 의사 결정 사회 리스크 통합 주장 오늘날 비즈니스 조언 아래 이메일 대화 편집 HBR Must Reads on Strategy Updated and Expanded 수록 Strategy in Hyperpolitical World 처음 발표 결론 정치 비즈니스 교차점 전망 예측 현실 오늘날 비즈니스 정치 명제 유효 예측 생각 정치 비즈니스 교차점 쟁점 경영자 사회 양극 생산 침공 비즈니스 문제 자신 입장 대응 목록 갈등 고조 대중국 경쟁 심화 시민 자유 위협 지속 가능 문제 글로벌 합의 후퇴 AI 고용 거대 그림자 문제 신중 입장 사회 논란 관세 수출입 금지 인재 확보 비자 제한 형태 직접 실질 영향 정치 이익 일치 전제 사회 정치 요인 전략 고정 변수 취급 제품 투자자 협의 비즈니스 이슈 본업 시대 정치 지정학 윤리 비즈니스 전략 정치 입장 위험 판단 기준 가치 CEO 사회 이슈 목소리 논의 자리 진행 논의 상당 다양 문제 입장 표명 요구 촉발 당시 대화 핵심 자신 신념 해당 이슈 전문 이슈 사업 고려 사안 입장 선택 순진 접근 입장 표명 위험 한계 간과 위험 이슈 개인 입장 합의 부재 내부 갈등 분열 입장 표명 매출 트랜스젠더 플루 기용 프로모션 특정 이슈 지지자 사이 추가 행동 기대 기대 충족 입장 상황 번복 신뢰 논란 이슈 입장 정치 취약 실질 사업 비용 발생 마찬가지 교육 현장 부모 권리 반대 세금 혜택 대표 오늘날 사회 정치 이슈 입장 고민 결정 적극 행동 필요 상황 사업 미래 전망 영향 정치 이슈 영향력 행사 위치 정치 개입 GPU 대중국 수출 금지 강경 성명 대신 수출 규제 제품 수정 매출 정치 세계 최선 전략 선택 실행 행동 원칙 수정 원칙 전략 선택 원칙 수립 윤리 문제 조기 업계 안팎 협력 환경 주도 형성 선택 입장 일관 소통 실행 실수 선택 L. 원칙 입장 고민 필요 정치 연루 비용 입장 실효 정치 비즈니스 경험 원칙 유효 생각 원칙 합리 예측 전개 구체 상황 도움 윤리 정치 문제 논란 사안 흐름 영향 개별 감당 문제 해결 주체 연대 정치 사회 이슈 현실 접근 사전 검토 입장 소통 일관 유지 자충수 전략 정치 예측 가능 영역 발생 실수 합리 태도 사이 정치 분석 인재 프로세스 강화 정치 전략 문제 학습 역사 유례 국면 사회 질서 평화 법치주의 과학 신뢰 비즈니스 전체 의존 근본 사회 정치 토대 위협 시대 자신 이익 토대 집단 주장 설득력 사회 대신 정치 선택 민주 정당성 언론 자유 시민 대화 민주주의 제도 지지 적극 투표 유급 휴가 제공 자원 봉사 활동 장려 시민 참여 지원 정보 허브 자신 정치 신념 현실 정치 환경 전략 수립 실행 정치 전략 정면 충돌 경쟁 정치 이해관계 비즈니스 필요 정치 흐름 개인 신념 사이 긴장 존재 균형 CEO 핵심 역할 번영 사회 환경 정합 유지 상황 사회 개인 차원 완벽 정합 실현 가능 과정 실용주의 유연성 모순 긴장 동적 중요 전제 조건 행동 원칙 반영 정치 환경 변화 시대 사실 인식 이해 갱신 개인 직업 비즈니스 정치 분리 가능 조화 공존 비즈니스 정치 분리 가능 비즈니스 개인 차원 정치 긴장 최소 견해 사람 효과 정책 상호 존중 생산 협력 환경 존중 상호 작용 규범 실천 정치 신념 사람 교류 공통점 인식 상호 존중 사람 이슈 표면 입장 이상 양극 완화 논쟁 주제 영역 교류 기회 동호회 활동 상호 존중 이해 효과 발휘'

## KeyBERT + BERTopic 사용

- 노이즈 데이터 제거, 불용어 사전 적용된 각각의 컬럼이 생성된 df_hbr_date 데이터프레임에 대해서<br> 전체 데이터를 사용하지 않고, 랜덤하게 20개 추출해 복사본을 만들어서 KeyBERT + BERTopic 수행

In [ ]:
# df_hbr_date에서 랜덤하게 20개 행 추출 후 복사본 생성
df_20 = df_hbr_date.sample(n=20, random_state=42).copy()

# 인덱스 정리
df_20 = df_20.reset_index(drop=True)

# 결과 확인
print("df_hbr_date 전체 데이터 개수:", len(df_hbr_date))
print("df_20 데이터 개수:", len(df_20))

df_20.head()

df_hbr_date 전체 데이터 개수: 1267
df_20 데이터 개수: 20

,title,content,url,category,published_date,source,summary,clean_content,analysis_content
0,가짜 뉴스에 대처하는 법,artist\nJoseph Ernst\n작품에 대해 |\n넘쳐나는 정보를 신뢰하기 ...,https://www.hbrkorea.com/article/view/atype/ma...,위기관리,2025. 9-10월호,HBR Korea,"넘쳐나는 정보를 신뢰하기 어려운 시대, 사이드라인 컬렉티브(Sideline Coll...",artist Joseph Ernst 작품에 대해 | 넘쳐나는 정보를 신뢰하기 어려운...,artist Joseph Ernst 작품 정보 신뢰 시대 라인 뉴스 세상 상상 가짜...
1,"월마트, 공급업체와의 협상을 자동화하다",요약\n많은 기업이 물품을 조달할 때 공급 업체와 협상할 시간이 부족하다고 이야기한...,https://www.hbrkorea.com/article/view/atype/di...,운영관리,2023. 1. 13.,HBR Korea,많은 기업이 물품을 조달할 때 공급 업체와 협상할 시간이 부족하다고 이야기한다. 이...,요약 많은 기업이 물품을 조달할 때 공급 업체와 협상할 시간이 부족하다고 이야기한다...,요약 물품 조달 공급 업체 협상 시간 부족 이야기 고질 문제 구매 공급 업체 모두 ...
2,중간관리자들이 혁신을 주도하게 하라,비즈니스 혁신에 대한 전통적인 접근 방식인 하향식 지시와 상향식 실행은 더 이상 유...,https://www.hbrkorea.com/article/view/atype/di...,인사조직,2024. 7. 16.,HBR Korea,비즈니스 혁신에 대한 전통적인 접근 방식인 하향식 지시와 상향식 실행은 더 이상 유...,비즈니스 혁신에 대한 전통적인 접근 방식인 하향식 지시와 상향식 실행은 더 이상 유...,비즈니스 혁신 전통 접근 하향식 지시 상향식 실행 이상 유효 오늘날 지속 성과 혁신...
3,탁월한 존재감을 위한 새로운 규칙,탁월한 존재감을 위한 새로운 규칙\n오늘날의 리더를 위한 행동 가이드\n예비 리더들...,https://www.hbrkorea.com/article/view/atype/ma...,리더십,2024. 1-2월호,HBR Korea,"예비 리더들은 고위임원, 특히 최고경영진이 되기 위해 ‘임원급 존재감",탁월한 존재감을 위한 새로운 규칙 오늘날의 리더를 위한 행동 가이드 예비 리더들은 ...,존재감 규칙 오늘날 행동 가이드 예비 고위 임원 최고 임원 존재감 executive...
4,부업을 메인 직업으로 삼아야 할까?,Illustrations by\nJori Bolton\n부업을 메인 직업으로 삼아야...,https://www.hbrkorea.com/article/view/atype/ma...,자기계발,2025. 3-4월호,HBR Korea,"마이클 A. 스탠코, 제프리 M. 폴락, 알렉산더 스타우브",Illustrations by Jori Bolton 부업을 메인 직업으로 삼아야 할...,Illustrations by Jori Bolton 부업 메인 직업 A. M. HB...

## KeyBERT 키워드 추출

### 사용 데이터프레임
- `df_20`

### 사용 컬럼
- `analysis_content`

`analysis_content` 컬럼은 노이즈 제거, 명사 추출, 불용어 제거가 완료된 분석용 텍스트이다.

### 추출 조건
- Kiwi 형태소 분석 결과 중 `NNG` 일반명사만 사용한다.
- 한 글자 단어는 제거한다.
- 불용어 사전에 포함된 단어는 제거한다.
- KeyBERT 입력 텍스트는 `NNG`만 남긴 텍스트를 사용한다.

### 추출 방식
- KeyBERT를 사용하여 문서별 핵심 키워드를 추출한다.
- 키워드는 1개 단어로 구성된 단어만 추출한다.
- 문서 1개당 상위 10개의 키워드를 추출한다.

### 결과 컬럼
- `keybert_keyword_scores`  
  - 키워드와 유사도 점수 정보를 함께 저장한다.

- `keybert_keywords`  
  - 키워드만 리스트 형태로 저장한다.

### 주의사항
- `NNG` 일반명사만 사용하면 `AI`, `ROI`, `CFO`와 같은 영어 약어는 제외될 수 있다.
- 영어 약어까지 키워드로 사용하려면 `NNG`와 함께 `SL` 품사를 포함해야 한다.

In [ ]:
!pip install keybert sentence-transformers kiwipiepy

from keybert import KeyBERT
from kiwipiepy import Kiwi
import pandas as pd


# 형태소 분석기 초기화
kiwi = Kiwi()

# KeyBERT 모델 초기화
kw_model = KeyBERT(model="paraphrase-multilingual-MiniLM-L12-v2")


def extract_nng_text(text):
    """
    입력 텍스트에서 NNG(일반명사)만 추출하여
    KeyBERT 입력용 문자열로 변환하는 함수
    """
    if pd.isna(text):
        return ""

    text = str(text).strip()

    if text == "":
        return ""

    words = []

    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사만 사용
        if pos == "NNG":

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            words.append(word)

    return " ".join(words)


def extract_keybert_keywords(text):
    # 값이 비어 있거나 NaN인 경우 빈 리스트 반환
    if pd.isna(text):
        return []

    # NNG 일반명사만 남긴 텍스트 생성
    nng_text = extract_nng_text(text)

    # NNG 추출 결과가 비어 있으면 빈 리스트 반환
    if nng_text == "":
        return []

    # KeyBERT 키워드 추출
    keywords = kw_model.extract_keywords(
        nng_text,
        keyphrase_ngram_range=(1, 1),  # 1개 단어 키워드만 추출
        stop_words=None,               # 불용어는 위에서 직접 제거했으므로 None
        top_n=10                       # 문서 1개당 상위 10개 키워드 추출
    )

    return keywords


# analysis_content 컬럼을 기준으로 KeyBERT 키워드 추출
df_20["keybert_keyword_scores"] = df_20["analysis_content"].apply(
    extract_keybert_keywords
)

# 키워드만 따로 리스트 형태로 저장
df_20["keybert_keywords"] = df_20["keybert_keyword_scores"].apply(
    lambda keywords: [keyword for keyword, score in keywords]
)

# 결과 확인
df_20[
    [
        "content",
        "clean_content",
        "analysis_content",
        "keybert_keywords",
        "keybert_keyword_scores"
    ]
].head()

Requirement already satisfied: keybert in /usr/local/lib/python3.12/dist-packages (0.9.0)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.5.1)
Requirement already satisfied: kiwipiepy in /usr/local/lib/python3.12/dist-packages (0.23.1)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from keybert) (2.0.2)
Requirement already satisfied: rich>=10.4.0 in /usr/local/lib/python3.12/dist-packages (from keybert) (13.9.4)
Requirement already satisfied: scikit-learn>=0.22.2 in /usr/local/lib/python3.12/dist-packages (from keybert) (1.6.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: kiwipiepy_model<0.24,>=0.23 in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (0.23.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.25.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=10.4.0->keybert) (2.20.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.2->keybert) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=10.4.0->keybert) (0.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (8.4.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (1.5.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

,content,clean_content,analysis_content,keybert_keywords,keybert_keyword_scores
0,artist\nJoseph Ernst\n작품에 대해 |\n넘쳐나는 정보를 신뢰하기 ...,artist Joseph Ernst 작품에 대해 | 넘쳐나는 정보를 신뢰하기 어려운...,artist Joseph Ernst 작품 정보 신뢰 시대 라인 뉴스 세상 상상 가짜...,"[폭로, 언급, 진짜, 소개, 무료, 세상, 시나리오, 서한, 제약사, 광고]","[(폭로, 0.5142), (언급, 0.4906), (진짜, 0.4643), (소개..."
1,요약\n많은 기업이 물품을 조달할 때 공급 업체와 협상할 시간이 부족하다고 이야기한...,요약 많은 기업이 물품을 조달할 때 공급 업체와 협상할 시간이 부족하다고 이야기한다...,요약 물품 조달 공급 업체 협상 시간 부족 이야기 고질 문제 구매 공급 업체 모두 ...,"[계약서, 계약, 협상, 비즈니스, 거래, 업체, 구매자, 세일, 경영, 체결]","[(계약서, 0.6316), (계약, 0.6269), (협상, 0.6267), (비..."
2,비즈니스 혁신에 대한 전통적인 접근 방식인 하향식 지시와 상향식 실행은 더 이상 유...,비즈니스 혁신에 대한 전통적인 접근 방식인 하향식 지시와 상향식 실행은 더 이상 유...,비즈니스 혁신 전통 접근 하향식 지시 상향식 실행 이상 유효 오늘날 지속 성과 혁신...,"[혁신, 변혁, 발전, 개선, 전략, 변화, 돌파구, 산업, 비즈니스, 개념]","[(혁신, 0.7011), (변혁, 0.4939), (발전, 0.4886), (개선..."
3,탁월한 존재감을 위한 새로운 규칙\n오늘날의 리더를 위한 행동 가이드\n예비 리더들...,탁월한 존재감을 위한 새로운 규칙 오늘날의 리더를 위한 행동 가이드 예비 리더들은 ...,존재감 규칙 오늘날 행동 가이드 예비 고위 임원 최고 임원 존재감 executive...,"[규범, 규칙, 근무, 콘퍼런스, 소개, 참석자, 상황, 말솜씨, 프로페셔널, 리더십]","[(규범, 0.5207), (규칙, 0.5112), (근무, 0.5105), (콘퍼..."
4,Illustrations by\nJori Bolton\n부업을 메인 직업으로 삼아야...,Illustrations by Jori Bolton 부업을 메인 직업으로 삼아야 할...,Illustrations by Jori Bolton 부업 메인 직업 A. M. HB...,"[경영대, 회사, 관리, 컴퍼니, 경영, 전문, 근무, 본사, 사무실, 설립]","[(경영대, 0.6085), (회사, 0.5734), (관리, 0.5727), (컴..."

In [ ]:
# df_20의 0번째 행에 있는 keybert_keyword_scores 컬럼 값 확인
df_20.loc[, "keybert_keyword_scores"]

NameError: name 'df_20' is not defined

## BERTopic 토픽 모델링

### 사용 데이터프레임
- `df_20`

### 사용 컬럼
- `clean_content`

`clean_content` 컬럼은 노이즈 제거는 완료되었지만, 문장 형태가 유지된 본문 데이터이다.

### 토픽 키워드 추출 조건
- Kiwi 형태소 분석 결과 중 `NNG` 일반명사만 사용한다.
- 토픽을 설명하는 키워드는 1개 단어로 구성된 단어만 사용한다.
- 불용어 사전에 포함된 단어는 제거한다.

### 목적
- 본문 데이터를 의미적으로 비슷한 토픽끼리 묶는다.
- 각 토픽을 대표하는 주요 키워드를 추출한다.

### 주의사항
- 현재 사용하는 `df_20`은 20개 샘플 데이터이다.
- 따라서 전체 데이터를 사용했을 때보다 토픽 분류 품질이 낮을 수 있다.
- 현재 단계에서는 BERTopic 코드가 정상적으로 작동하는지 확인하는 테스트 용도로 사용한다.

In [ ]:
!pip install bertopic
from bertopic import BERTopic
from sklearn.feature_extraction.text import CountVectorizer
from sentence_transformers import SentenceTransformer
from umap import UMAP
from hdbscan import HDBSCAN
import pandas as pd

# ============================================================
# 1. BERTopic 토픽 키워드 추출용 토크나이저
# ============================================================
# clean_content 문장은 BERTopic 임베딩 입력으로 그대로 사용한다.
# 단, 토픽 대표 키워드를 뽑을 때는 Kiwi 형태소 분석을 적용한다.
# 여기서는 NNG(일반명사)만 토픽 키워드 후보로 사용한다.
# ============================================================

def kiwi_tokenizer(text):
    tokens = []

    if pd.isna(text):
        return tokens

    text = str(text)

    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사만 사용
        if pos == "NNG":

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            tokens.append(word)

    return tokens


# ============================================================
# 2. BERTopic 입력 데이터 준비
# ============================================================
# df_20의 clean_content 컬럼에서 비어 있지 않은 문장만 사용
# ============================================================

df_bertopic = df_20[df_20["clean_content"].notna()].copy()
df_bertopic = df_bertopic[
    df_bertopic["clean_content"].astype(str).str.strip() != ""
].copy()

docs = df_bertopic["clean_content"].tolist()

print("BERTopic에 입력할 문서 개수:", len(docs))


# ============================================================
# 3. CountVectorizer 설정
# ============================================================
# 토픽별 대표 키워드를 뽑을 때 사용할 토큰화 방식 지정
# ngram_range=(1, 1)이므로 1개 단어 키워드만 생성
# ============================================================

vectorizer_model = CountVectorizer(
    tokenizer=kiwi_tokenizer,
    token_pattern=None,
    ngram_range=(1, 1),
    min_df=1,
    max_df=0.9
)


# ============================================================
# 4. 임베딩 모델 설정
# ============================================================
# clean_content 문장의 의미를 벡터로 변환하기 위한 다국어 임베딩 모델 사용
# ============================================================

embedding_model = SentenceTransformer("paraphrase-multilingual-MiniLM-L12-v2")


# ============================================================
# 5. UMAP / HDBSCAN 설정
# ============================================================
# df_20은 샘플 데이터 20개만 사용하므로,
# 작은 데이터에서도 토픽이 생성될 수 있도록 값을 낮게 설정
# ============================================================

umap_model = UMAP(
    n_neighbors=5,
    n_components=2,
    min_dist=0.0,
    metric="cosine",
    random_state=42
)

hdbscan_model = HDBSCAN(
    min_cluster_size=2,
    min_samples=1,
    metric="euclidean",
    prediction_data=True
)


# ============================================================
# 6. BERTopic 모델 생성 및 학습
# ============================================================

topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer_model,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    language="multilingual",
    calculate_probabilities=True,
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)


# ============================================================
# 7. df_20에 BERTopic 결과 저장
# ============================================================
# topic 번호를 원본 df_20의 해당 행에 다시 저장
# ============================================================

df_bertopic["bertopic_topic"] = topics

# df_20에 bertopic_topic 컬럼 생성
df_20["bertopic_topic"] = None

# clean_content가 존재했던 행에만 topic 결과 저장
df_20.loc[df_bertopic.index, "bertopic_topic"] = df_bertopic["bertopic_topic"]


# ============================================================
# 8. 토픽 정보 확인
# ============================================================

topic_info = topic_model.get_topic_info()

print("생성된 토픽 정보:")
display(topic_info)

# df_20 결과 확인
df_20[["clean_content", "bertopic_topic"]].head()

Requirement already satisfied: bertopic in /usr/local/lib/python3.12/dist-packages (0.17.4)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.43)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.12)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.5.1)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.3)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2026.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.4)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (26.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (5.0.0)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (1.16.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.11.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.6.0)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: typer>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.25.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.7.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.13.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2026.5.20)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (3.15)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (8.4.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.0.4)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer>=0.20.0->huggingface-hub>=0.23.0->sentence-transformers>=0.4.1->bertopic) (0.1.2)
BERTopic에 입력할 문서 개수: 20

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
2026-05-27 03:43:44,641 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

2026-05-27 03:43:49,525 - BERTopic - Embedding - Completed ✓
2026-05-27 03:43:49,526 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-05-27 03:44:01,104 - BERTopic - Dimensionality - Completed ✓
2026-05-27 03:44:01,106 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-05-27 03:44:01,129 - BERTopic - Cluster - Completed ✓
2026-05-27 03:44:01,141 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-05-27 03:44:08,362 - BERTopic - Representation - Completed ✓

생성된 토픽 정보:

,Topic,Count,Name,Representation,Representative_Docs
0,0,10,0_브랜드_뉴스_가짜_제품,"[브랜드, 뉴스, 가짜, 제품, 생성, 업체, 에이전트, 협상, 지역, 알고리즘]",[생성형 AI가 쇼핑 방식을 변화시키기 시작했다. 사람들이 웹사이트를 스크롤하거나 ...
1,1,4,1_중간_변화_혁신_성장,"[중간, 변화, 혁신, 성장, 최고, 영업, 인정, 인재, 비즈니스, 문화]",[‘행복한 직원이 행복한 고객을 만든다’는 말은 익히 들어왔지만 새로운 데이터는 직...
2,2,4,2_최고_임원_연구진_진정,"[최고, 임원, 연구진, 진정, 여성, 회의, 책임자, 혁신, 참가자, 음악]",[직장에 '온전한 자신'을 가져오라는 생각은 종종 아름다운 말처럼 포장되곤 하지만 ...
3,3,2,3_여성_남성_정책_신뢰도,"[여성, 남성, 정책, 신뢰도, 영향, 사회, 고용주, 참가자, 보상, 직장]",[회사가 새로운 채용 공고를 냈다고 가정해 보겠다. 지원자를 열심히 검토하고 몇 명...

                                       clean_content bertopic_topic
0  artist Joseph Ernst 작품에 대해 | 넘쳐나는 정보를 신뢰하기 어려운...              0
1  요약 많은 기업이 물품을 조달할 때 공급 업체와 협상할 시간이 부족하다고 이야기한다...              0
2  비즈니스 혁신에 대한 전통적인 접근 방식인 하향식 지시와 상향식 실행은 더 이상 유...              1
3  탁월한 존재감을 위한 새로운 규칙 오늘날의 리더를 위한 행동 가이드 예비 리더들은 ...              2
4  Illustrations by Jori Bolton 부업을 메인 직업으로 삼아야 할...              0

## DBR 데이터에도 동일하게 적용

In [ ]:
import pandas as pd

# CSV 파일 불러오기
df_dbr = pd.read_csv(csv_files[1])

# 데이터 크기 확인
print("데이터 크기:", df_dbr.shape)

# 컬럼 확인
print("컬럼 목록:")
print(df_dbr.columns)

# 마지막 5개 행 확인
df_dbr.head()

데이터 크기: (11273, 7)
컬럼 목록:
Index(['title', 'content', 'url', 'category', 'published_date', 'source',
       'summary'],
      dtype='object')

,title,content,url,category,published_date,source,summary
0,‘호모 파베르’의 마지막 도구,아마존 설립자 제프 베이조스는 오래전부터 SF(과학소설) 팬이었습니다. 아마존이 2...,https://dbr.donga.com/article/view/1904/articl...,Editor’s Letter,441호 (2026년 5월 Issue 2),DBR,아마존 설립자 제프 베이조스는 오래전부터 SF(과학소설) 팬이었습니다. 아마존이 2...
1,"AI 시대, HR의 진짜 질문은 ‘누가 책임질까’",“AI를 HR(인사·조직 관리)에 어디까지 써야 할까요?”\n최근 기업 경영진을 만...,https://dbr.donga.com/article/view/1801/articl...,DBR Column,441호 (2026년 5월 Issue 2),DBR,“AI를 HR(인사·조직 관리)에 어디까지 써야 할까요?”\n최근 기업 경영진을 만...
2,공감 잘하는 리더보다 냉혹한 리더가구성원 처벌 상황선 ‘유능’ 평가받아,▶ Based on “Who Avoids Punishment? How Discret...,https://dbr.donga.com/article/view/1306/articl...,Leadership,441호 (2026년 5월 Issue 2),DBR,▶ Based on “Who Avoids Punishment? How Discret...
3,저가 수입품 공세-지정학 위기 때마케팅 강한 기업이 고객 이탈 방어,▶ Based on “Can Marketing Enable Firms to Coun...,https://dbr.donga.com/article/view/1202/articl...,Marketing,441호 (2026년 5월 Issue 2),DBR,▶ Based on “Can Marketing Enable Firms to Coun...
4,“매력적인 사람이 더 사교적일 것”리더 선발에 외모 편향 효과 작용,▶ Based on “The Beauty Bias and Leader Emergen...,https://dbr.donga.com/article/view/1201/articl...,Organizational Behavior,441호 (2026년 5월 Issue 2),DBR,▶ Based on “The Beauty Bias and Leader Emergen...

In [ ]:
print(df_dbr.isna().sum())
print(df_dbr.dtypes)

title                0
content              0
url                  0
category          3243
published_date       0
source               0
summary              0
dtype: int64
title             object
content           object
url               object
category          object
published_date    object
source            object
summary           object
dtype: object

In [ ]:
print("=" * 60)
print("[2단계] df_dbr 데이터 범위 맞추기")
print("=" * 60)

# published_date 컬럼을 문자열로 변환하고 앞뒤 공백 제거
df_dbr["published_date"] = df_dbr["published_date"].astype(str).str.strip()

# 2023년, 2024년, 2025년, 2026년이 포함된 행만 필터링 후 복사본 생성
df_dbr_date = df_dbr[
    df_dbr["published_date"].str.contains(
        "2023년|2024년|2025년|2026년",
        regex=True,
        na=False
    )
].copy()

print("-" * 60)
print("[결과 확인]")
print("-" * 60)

# 결과 확인
print("원본 데이터 개수:", len(df_dbr))
print("2023~2026 데이터 개수:", len(df_dbr_date))

df_dbr_date.head()

============================================================
[2단계] df_dbr 데이터 범위 맞추기
============================================================
------------------------------------------------------------
[결과 확인]
------------------------------------------------------------
원본 데이터 개수: 11273
2023~2026 데이터 개수: 1415

,title,content,url,category,published_date,source,summary
0,‘호모 파베르’의 마지막 도구,아마존 설립자 제프 베이조스는 오래전부터 SF(과학소설) 팬이었습니다. 아마존이 2...,https://dbr.donga.com/article/view/1904/articl...,Editor’s Letter,441호 (2026년 5월 Issue 2),DBR,아마존 설립자 제프 베이조스는 오래전부터 SF(과학소설) 팬이었습니다. 아마존이 2...
1,"AI 시대, HR의 진짜 질문은 ‘누가 책임질까’",“AI를 HR(인사·조직 관리)에 어디까지 써야 할까요?”\n최근 기업 경영진을 만...,https://dbr.donga.com/article/view/1801/articl...,DBR Column,441호 (2026년 5월 Issue 2),DBR,“AI를 HR(인사·조직 관리)에 어디까지 써야 할까요?”\n최근 기업 경영진을 만...
2,공감 잘하는 리더보다 냉혹한 리더가구성원 처벌 상황선 ‘유능’ 평가받아,▶ Based on “Who Avoids Punishment? How Discret...,https://dbr.donga.com/article/view/1306/articl...,Leadership,441호 (2026년 5월 Issue 2),DBR,▶ Based on “Who Avoids Punishment? How Discret...
3,저가 수입품 공세-지정학 위기 때마케팅 강한 기업이 고객 이탈 방어,▶ Based on “Can Marketing Enable Firms to Coun...,https://dbr.donga.com/article/view/1202/articl...,Marketing,441호 (2026년 5월 Issue 2),DBR,▶ Based on “Can Marketing Enable Firms to Coun...
4,“매력적인 사람이 더 사교적일 것”리더 선발에 외모 편향 효과 작용,▶ Based on “The Beauty Bias and Leader Emergen...,https://dbr.donga.com/article/view/1201/articl...,Organizational Behavior,441호 (2026년 5월 Issue 2),DBR,▶ Based on “The Beauty Bias and Leader Emergen...

In [ ]:
import re
import pandas as pd

print("=" * 60)
print("[3단계] DBR 본문 데이터 노이즈 제거")
print("=" * 60)


def clean_content(text):
    # content 값이 비어 있거나 NaN인 경우 빈 문자열로 처리
    if pd.isna(text):
        return ""

    # 숫자, NaN 등이 섞여 있을 가능성을 대비해 문자열로 변환
    text = str(text)

    # 원문 | 이후의 푸터 영역 전체 제거
    # 예: 원문 | https://... 이후 URL, 저자소개, 에디팅 정보 제거
    text = re.sub(
        r"(?m)^\s*원문\s*\|[\s\S]*$",
        " ",
        text
    )

    # 이메일 주소 제거
    text = re.sub(
        r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}",
        " ",
        text
    )

    # URL 제거
    text = re.sub(
        r"http[s]?://\S+|www\.\S+",
        " ",
        text
    )

    # 실제 줄바꿈, 엔터, 탭 문자 제거
    text = re.sub(r"[\n\r\t]", " ", text)

    # 문자열 형태로 저장된 줄바꿈 문자 제거
    text = text.replace("\\n", " ")

    # 이스케이프된 따옴표 제거
    text = re.sub(r"\\['\"]", " ", text)

    # 본문에 남아 있는 \ 기호 제거
    text = re.sub(r"\\+", " ", text)

    # <내용> 형태 제거
    text = re.sub(r"<[^>]*>", " ", text)

    # 재판매 및 DB 금지 문구 제거
    text = re.sub(
        r"\*?\s*재판매\s*및\s*DB\s*금지",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 대괄호로 묶인 출처/지역/언론사/광고 정보 제거
    text = re.sub(r"\[[^\]]*\]", " ", text)

    # 소괄호로 묶인 사진 설명, 출처, 부가 설명 제거
    text = re.sub(r"\([^)]*\)", " ", text)

    # 기사 본문에 포함된 날짜 형식 제거
    text = re.sub(r"\d{4}\.\d{1,2}\.\d{1,2}\.?", " ", text)

    # 한글 이름 + 기자 표현 제거
    text = re.sub(r"[가-힣]{2,4}\s*기자", " ", text)

    # 기자 = 형태 제거
    text = re.sub(r"기자\s*=", " ", text)

    # 저작권, 무단전재, 재배포 금지, 제보 문구 제거
    text = re.sub(
        r"(무단\s*전재|재배포\s*금지|ⓒ|Copyright|제보를 기다립니다)",
        " ",
        text,
        flags=re.IGNORECASE
    )

    # 불필요한 특수기호 제거
    text = re.sub(r"[▲▶*=…]", " ", text)

    # 여러 개의 공백을 하나의 공백으로 정리
    text = re.sub(r"\s+", " ", text)

    return text.strip()


# content 컬럼을 전처리한 뒤 clean_content 컬럼에 저장
df_dbr_date["clean_content"] = df_dbr_date["content"].apply(clean_content)

print("-" * 60)
print("[전처리 결과 확인]")
print("-" * 60)

# 전처리 전 content와 전처리 후 clean_content 비교 확인
df_dbr_date[["content", "clean_content"]].tail()

============================================================
[3단계] DBR 본문 데이터 노이즈 제거
============================================================
------------------------------------------------------------
[전처리 결과 확인]
------------------------------------------------------------

,content,clean_content
1410,Article at a Glance\n기업에서 발생하는 부정행위에 대해 예방뿐만 아...,Article at a Glance 기업에서 발생하는 부정행위에 대해 예방뿐만 아니...
1411,편집자주\n이 글은 2022년 6월21일 MIT 슬론매니지먼트리뷰(SMR) 온라인에...,편집자주 이 글은 2022년 6월21일 MIT 슬론매니지먼트리뷰 온라인에 실린 ‘T...
1412,Article at a Glance\n모든 게 동시다발적으로 변하는 경영 환경에서 ...,Article at a Glance 모든 게 동시다발적으로 변하는 경영 환경에서 한...
1413,Article at a Glance\n갤럽이 발표하는 ‘세계 감정 보고서’에 따르면...,Article at a Glance 갤럽이 발표하는 ‘세계 감정 보고서’에 따르면 ...
1414,에베레스트산 정상에 도전하는 이들에게는 한 가지 절대적인 규칙이 있다. 바로 ‘반환...,에베레스트산 정상에 도전하는 이들에게는 한 가지 절대적인 규칙이 있다. 바로 ‘반환...

In [ ]:
!pip install kiwipiepy

from kiwipiepy import Kiwi
import pandas as pd

print("=" * 60)
print("[4단계] df_dbr_date 명사 추출 및 불용어 제거")
print("=" * 60)

# 형태소 분석기 초기화
kiwi = Kiwi()


# ============================================================
# HBR / DBR 아티클용 불용어 사전
# ============================================================
# 뉴스 기사용 불용어에서 언론사/기자/보도 표현은 줄이고,
# 아티클 구조상 자주 반복되는 표현을 추가한 버전
# ============================================================

STOPWORDS = {
    # ============================================================
    # 1. 일반 불용어
    # ============================================================
    "것", "수", "등", "및", "때", "중", "더", "또",
    "관련", "경우", "대상", "약", "정도", "부분",
    "내용", "방식", "방법", "수준", "결과", "사례",

    # ============================================================
    # 2. 조사·연결·전환 표현
    # ============================================================
    "위해", "통해", "대한", "또한", "한편",
    "따라", "이에", "다만", "특히", "반면",
    "예를", "그러나", "하지만", "그리고", "따라서",
    "즉", "먼저", "마지막", "다음",

    # ============================================================
    # 3. 시점 표현
    # ============================================================
    "이번", "지난", "올해", "내년", "최근", "현재", "향후",
    "오늘", "내일", "이날", "이후", "이전", "초기",
    "단기", "장기", "매년",

    # ============================================================
    # 4. 아티클 구조 관련 표현
    # ============================================================
    "아티클", "필자", "저자", "본문", "원문",
    "에디팅", "설문조사", "설문", "조사", "연구",
    "인터뷰", "응답자", "대상자", "질문", "답변",
    "응답", "비율", "퍼센트",

    # ============================================================
    # 5. 순서·단계 서술 표현
    # ============================================================
    "첫번째", "두번째", "세번째", "네번째", "다섯번째",
    "여섯번째", "일곱번째",
    "단계", "요소", "구성", "항목", "모델",

    # ============================================================
    # 6. 인물명 및 직책 관련 단어
    # ============================================================
    "토머스", "대븐포트", "락스", "스리니바산",
    "김민수", "교수", "학과장", "방문", "연구원",
    "고문", "창립자", "공동", "최고운영책임자",

    # ============================================================
    # 7. 기관명·기업명
    # ============================================================
    "밥슨", "칼리지", "Babson", "College",
    "Metropoulos", "Institute", "Technology",
    "Entrepreneurship", "MIT", "Deloitte",
    "Return", "Institute", "Opera", "Solutions",
    "Scaled", "Agile", "Capital", "One",
    "Merck", "KGaA", "Schneider", "Electric",
    "Olympus", "Corporation", "Americas",
    "Ally", "Financial", "CarMax", "DBS",

    # ============================================================
    # 8. 아티클 서술 표현
    # ============================================================
    "말했다", "설명했다", "밝혔다", "전했다", "강조했다",
    "보고했다", "답했다", "응답했다", "꼽았다",
    "제시했다", "확인했다", "살펴봤다",
    "설명", "강조", "제시", "확인", "발견",
    "포함", "달성", "추구", "활용", "도입",
    "운영", "수행", "공개", "공유",

    # ============================================================
    # 9. 의미가 너무 넓은 추상어
    # ============================================================
    "기업", "조직", "리더", "경영진", "직원",
    "사용자", "고객", "업무", "경제", "재무"
}


# ============================================================
# 명사 추출 + 불용어 제거 함수
# ============================================================

def remove_stopwords_and_extract_nouns(text):
    # 값이 비어 있거나 NaN인 경우 빈 문자열 반환
    if pd.isna(text):
        return ""

    text = str(text)

    words = []

    # Kiwi 형태소 분석 수행
    for token in kiwi.tokenize(text):
        word = token.form
        pos = token.tag

        # NNG: 일반명사
        # SL: 영어/외국어 표현, 예: AI, ROI, CFO
        if pos in ["NNG", "SL"]:

            # 한 글자 단어 제거
            if len(word) <= 1:
                continue

            # 불용어 제거
            if word in STOPWORDS:
                continue

            words.append(word)

    return " ".join(words)


# clean_content 컬럼을 기준으로 명사 추출 및 불용어 제거
df_dbr_date["analysis_content"] = df_dbr_date["clean_content"].apply(
    remove_stopwords_and_extract_nouns
)

print("-" * 60)
print("[결과 확인]")
print("-" * 60)

# 결과 확인
df_dbr_date[["content", "clean_content", "analysis_content"]].head()

Collecting kiwipiepy
  Downloading kiwipiepy-0.23.1-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.3 kB)
Collecting kiwipiepy_model<0.24,>=0.23 (from kiwipiepy)
  Downloading kiwipiepy_model-0.23.0.tar.gz (88.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 88.0/88.0 MB 9.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (2.0.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kiwipiepy) (4.67.3)
Downloading kiwipiepy-0.23.1-cp39-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 10.5 MB/s eta 0:00:00
Building wheels for collected packages: kiwipiepy_model
  Building wheel for kiwipiepy_model (setup.py) ... done
  Created wheel for kiwipiepy_model: filename=kiwipiepy_model-0.23.0-py3-none-any.whl size=88067826 sha256=7bd528ae727facdc651bc7e964cb562031bfb4105e650785336636fabad5f3a4
  Stored in directory: /root/.cache/pip/wheels/f2/94/da/ff88b4c2305cd1f3effc8001b5f42f16dc9931bcd84d1e77c3
Successfully built kiwipiepy_model
Installing collected packages: kiwipiepy_model, kiwipiepy
Successfully installed kiwipiepy-0.23.1 kiwipiepy_model-0.23.0
============================================================
[4단계] df_dbr_date 명사 추출 및 불용어 제거
============================================================
------------------------------------------------------------
[결과 확인]
------------------------------------------------------------

,content,clean_content,analysis_content
0,아마존 설립자 제프 베이조스는 오래전부터 SF(과학소설) 팬이었습니다. 아마존이 2...,아마존 설립자 제프 베이조스는 오래전부터 SF 팬이었습니다. 아마존이 2010년대 ...,설립자 오래전 SF 개발 시작 당시 엔지니어 목표 스타트 컴퓨터 함장 컴퓨터 거리 ...
1,“AI를 HR(인사·조직 관리)에 어디까지 써야 할까요?”\n최근 기업 경영진을 만...,“AI를 HR 에 어디까지 써야 할까요?” 최근 기업 경영진을 만나면 빠지지 않고 ...,AI HR 등장 함정 자체 AI 기술 범위 문제 축소 AI 적극 실험 글로벌 기술 ...
2,▶ Based on “Who Avoids Punishment? How Discret...,Based on “Who Avoids Punishment? How Discretio...,Based on Who Avoids Punishment How Discretion ...
3,▶ Based on “Can Marketing Enable Firms to Coun...,Based on “Can Marketing Enable Firms to Counte...,Based on Can Marketing Enable Firms to Counter...
4,▶ Based on “The Beauty Bias and Leader Emergen...,Based on “The Beauty Bias and Leader Emergence...,Based on The Beauty Bias and Leader Emergence ...

In [ ]:
df_dbr_date["analysis_content"][0]

'설립자 오래전 SF 개발 시작 당시 엔지니어 목표 스타트 컴퓨터 함장 컴퓨터 거리 시스템 일부 IT 분석가 타이머 음악 재생 음성 기기 폄하 스타트렉의 컴퓨터 타이머 기계 플러스 도전 의도 파악 행동 진짜 에이전트 AI 가시 경영학 역사 에이전트 단어 오랫동안 고유 무게 주인 대리인 이론 의사 결정 권한 위임 발생 이해관계 충돌 경제학 이론 주주 CEO 변호사 정보 권한 대칭 분포 위임 관계 적용 이론 오랫동안 인간 인간 설계 권한 위임 관계 전제 발전 전제 대리인 자리 인간 AI 등장 인간 호모 베르 도구 인간 인류 돌도끼 바퀴 발명 증기 기관 설계 도구 판단 행동 망치 방향 결정 자동차 목적지 선택 AI 에이전트 처음 인간 의사 결정 위임 실행 도구 등장 AI 에이전트 호모 베르 도구 인간 도구 처음 인간 대리 존재 의미 이상 인간 도구 유일 주인 의미 AI 에이전트 챗봇 출장 준비 한마디 항공편 비교 숙소 예약 미팅 전날 저녁 식당 캘린더 주의력 의도 에이전트 이동 역사 전환점 목격 대형 플랫폼 시선 광고주 판매 시장 구축 AI 에이전트 시선 의도 거래 출발점 의도 AI 대신 실행 전환 플랫폼 권력 약화 현실 반대 방향 전개 테크 에이전트 담장 정원 구축 시작 자사 소셜 플랫폼 중심 AI 에이전트 내재 쇼핑 에이전트 자사 결제 카탈로그 신원 시스템 연결 인간 기존 플랫폼 이제 AI 에이전트 록인 플랫폼 진화 쇼핑 기능 결합 커머스 현주소 냉정 AI 대리인 비서 소비자 AI 추천 결제 권한 유통 산업 권력 지형 DBR 비즈니스 트렌드 AI 에이전트 시대 등장 대신 정의 담론 현실 시점 리포트 전선 지형도 주목'

In [ ]:
# df_dbr_date에서 상위 20개 행만 선택해서 복사본 생성
df_dbr_20 = df_dbr_date.head(20).copy()

# 결과 확인
print("df_dbr_date 데이터 개수:", len(df_dbr_date))
print("df_dbr_20 데이터 개수:", len(df_dbr_20))

df_dbr_20

df_dbr_date 데이터 개수: 1415
df_dbr_20 데이터 개수: 20

,title,content,url,category,published_date,source,summary,clean_content,analysis_content
0,‘호모 파베르’의 마지막 도구,아마존 설립자 제프 베이조스는 오래전부터 SF(과학소설) 팬이었습니다. 아마존이 2...,https://dbr.donga.com/article/view/1904/articl...,Editor’s Letter,441호 (2026년 5월 Issue 2),DBR,아마존 설립자 제프 베이조스는 오래전부터 SF(과학소설) 팬이었습니다. 아마존이 2...,아마존 설립자 제프 베이조스는 오래전부터 SF 팬이었습니다. 아마존이 2010년대 ...,설립자 오래전 SF 개발 시작 당시 엔지니어 목표 스타트 컴퓨터 함장 컴퓨터 거리 ...
1,"AI 시대, HR의 진짜 질문은 ‘누가 책임질까’",“AI를 HR(인사·조직 관리)에 어디까지 써야 할까요?”\n최근 기업 경영진을 만...,https://dbr.donga.com/article/view/1801/articl...,DBR Column,441호 (2026년 5월 Issue 2),DBR,“AI를 HR(인사·조직 관리)에 어디까지 써야 할까요?”\n최근 기업 경영진을 만...,“AI를 HR 에 어디까지 써야 할까요?” 최근 기업 경영진을 만나면 빠지지 않고 ...,AI HR 등장 함정 자체 AI 기술 범위 문제 축소 AI 적극 실험 글로벌 기술 ...
2,공감 잘하는 리더보다 냉혹한 리더가구성원 처벌 상황선 ‘유능’ 평가받아,▶ Based on “Who Avoids Punishment? How Discret...,https://dbr.donga.com/article/view/1306/articl...,Leadership,441호 (2026년 5월 Issue 2),DBR,▶ Based on “Who Avoids Punishment? How Discret...,Based on “Who Avoids Punishment? How Discretio...,Based on Who Avoids Punishment How Discretion ...
3,저가 수입품 공세-지정학 위기 때마케팅 강한 기업이 고객 이탈 방어,▶ Based on “Can Marketing Enable Firms to Coun...,https://dbr.donga.com/article/view/1202/articl...,Marketing,441호 (2026년 5월 Issue 2),DBR,▶ Based on “Can Marketing Enable Firms to Coun...,Based on “Can Marketing Enable Firms to Counte...,Based on Can Marketing Enable Firms to Counter...
4,“매력적인 사람이 더 사교적일 것”리더 선발에 외모 편향 효과 작용,▶ Based on “The Beauty Bias and Leader Emergen...,https://dbr.donga.com/article/view/1201/articl...,Organizational Behavior,441호 (2026년 5월 Issue 2),DBR,▶ Based on “The Beauty Bias and Leader Emergen...,Based on “The Beauty Bias and Leader Emergence...,Based on The Beauty Bias and Leader Emergence ...
5,전기차 등 기술 전환 가로막는 병목생태계 모두가 수익 낼 구조 필요,▶ Based on “Business models as bottlenecks: Ho...,https://dbr.donga.com/article/view/1203/articl...,Innovation,441호 (2026년 5월 Issue 2),DBR,▶ Based on “Business models as bottlenecks: Ho...,Based on “Business models as bottlenecks: How ...,Based on Business models as bottlenecks How th...
6,"AI 에이전트 시대, 플랫폼 패권의 이동",에이전트 친화적 인터페이스를 설계하라\n표준 프로토콜 참여해야 자사 상품 노출\nA...,https://dbr.donga.com/article/view/1101/articl...,Special Report,441호 (2026년 5월 Issue 2),DBR,현재 플랫폼은 사용자의 시선을 붙잡아 광고를 판매하는 주의력 경제(Attention...,에이전트 친화적 인터페이스를 설계하라 표준 프로토콜 참여해야 자사 상품 노출 Art...,에이전트 친화 인터페이스 설계 표준 프로토콜 참여 자사 상품 노출 Article a...
7,“AI 에이전트 통한 소액거래 결제 늘 것기업엔 고품질 인간 피드백이 핵심 자산”,Article at a Glance\nAI 에이전트 경제의 핵심 변화는 단순한 정보...,https://dbr.donga.com/article/view/1101/articl...,Interview: 美 마이크로소프트 리서치 경제학자 데이비드 로스차일드,441호 (2026년 5월 Issue 2),DBR,AI 에이전트 경제의 핵심 변화는 단순한 정보 처리 속도의 향상이 아니라 소비자와 ...,Article at a Glance AI 에이전트 경제의 핵심 변화는 단순한 정보 ...,Article at Glance AI 에이전트 핵심 변화 단순 정보 처리 속도 향상...
8,‘비서 넘어 대리인으로’ 에이전틱 커머스의 미래,한국선 AI 결제보다 상품 추천에 큰 기회\n신뢰 쌓여야 에이전트에 지갑 넘겨\nA...,https://dbr.donga.com/article/view/1101/articl...,Special Report,441호 (2026년 5월 Issue 2),DBR,에이전틱 커머스 전쟁이 본격화하고 있지만 AI는 아직 사람을 대신해 구매를 완결하는...,한국선 AI 결제보다 상품 추천에 큰 기회 신뢰 쌓여야 에이전트에 지갑 넘겨 Art...,AI 결제 상품 추천 기회 신뢰 에이전트 지갑 Article at Glance 커머...
9,새 경제 주체로 떠오른 AI 에이전트,조직의 ‘암묵지’를 데이터로 변환 필수\nAI-인간 팀 설계하고 권한 구조 다시 써...,https://dbr.donga.com/article/view/1101/articl...,Special Report,441호 (2026년 5월 Issue 2),DBR,AI 에이전트의 부상은 AI가 새로운 경제 주체로 편입되는 변화를 뜻한다. 이는 소...,조직의 ‘암묵지’를 데이터로 변환 필수 AI-인간 팀 설계하고 권한 구조 다시 써야...,데이터 변환 필수 AI 인간 설계 권한 구조 Article at Glance AI ...
10,매장 수 국내 1위로 성장한 버거 브랜드 맘스터치,6년간 체질 개선→리브랜딩→글로벌 확장\n사모펀드의 오퍼레이셔널 밸류업 통해 상생\...,https://dbr.donga.com/article/view/1901/articl...,DBR Case Study,441호 (2026년 5월 Issue 2),DBR,2019년 사모펀드 케이엘앤파트너스에 인수될 당시 맘스터치는 매장 수는 많지만 브랜...,6년간 체질 개선→리브랜딩→글로벌 확장 사모펀드의 오퍼레이셔널 밸류업 통해 상생 A...,체질 개선 리브랜딩 글로벌 확장 사모 펀드 오퍼레이셔널 밸류 상생 Article a...
11,적정 성능 갖춘 6000달러 저가 휴머노이드빠른 출시 후 시장 피드백 통해 지속 개선,Article at a Glance\n중국의 혁신 기업들이 글로벌 피지컬 AI 산업...,https://dbr.donga.com/article/view/1901/articl...,중국 AI 기업 케이스 스터디: 유니트리 로보틱스,441호 (2026년 5월 Issue 2),DBR,중국의 혁신 기업들이 글로벌 피지컬 AI 산업의 경쟁 구도를 재편하고 있다. 그 중...,Article at a Glance 중국의 혁신 기업들이 글로벌 피지컬 AI 산업의...,Article at Glance 혁신 글로벌 피지컬 AI 산업 경쟁 구도 재편 중심...
12,"“AI 기업, B2C 구독요금제로는 수익 한계다른 사업 없이 AI 성장에만 의존 땐...",Article at a Glance\n현재의 AI 붐은 골드러시에 비유할 수 있다....,https://dbr.donga.com/article/view/1203/articl...,DBR Thinkers’ Club - 앤디 우 하버드경영대학원 교수,441호 (2026년 5월 Issue 2),DBR,현재의 AI 붐은 골드러시에 비유할 수 있다. 하드웨어를 공급하는 반도체 기업(삽을...,Article at a Glance 현재의 AI 붐은 골드러시에 비유할 수 있다. ...,Article at Glance AI 골드러시 비유 하드웨어 공급 반도체 진입 장벽...
13,"총수의 정원, 모두의 공원으로 환원하다",Article at a Glance\n에도 시대를 상징하는 정원 ‘리쿠기엔’은 도쿠...,https://dbr.donga.com/article/view/1905/articl...,신현암의 정원 읽기,441호 (2026년 5월 Issue 2),DBR,Article at a Glance\n에도 시대를 상징하는 정원 ‘리쿠기엔’은 도쿠...,Article at a Glance 에도 시대를 상징하는 정원 ‘리쿠기엔’은 도쿠가...,Article at Glance 시대 상징 정원 막부 최후 몰락 정원 시대 신흥 창...
14,백성 살리려면 원수와도 손 잡을 수 있어야,Article at a Glance\n17세기 말 조선은 을병 대기근 앞에서 내부 ...,https://dbr.donga.com/article/view/1306/articl...,격변기의 국가 경영 : 을병 대기근 ②,441호 (2026년 5월 Issue 2),DBR,Article at a Glance\n17세기 말 조선은 을병 대기근 앞에서 내부 ...,Article at a Glance 17세기 말 조선은 을병 대기근 앞에서 내부 역...,Article at Glance 세기 기근 내부 역량 불구대천 원수 곡물 원조 요청...
15,다른 산을 오르기로 했다 外,다른 산을 오르기로 했다\n조너선 프랭클린 지음 · 강동혁 옮김\n복복서가 · 2만...,https://dbr.donga.com/article/view/1303/articl...,New Biz Books,441호 (2026년 5월 Issue 2),DBR,조너선 프랭클린 지음 · 강동혁 옮김 복복서가 · 2만5000원 연 매출 1조 원 ...,다른 산을 오르기로 했다 조너선 프랭클린 지음 · 강동혁 옮김 복복서가 · 2만50...,매출 규모 글로벌 패션 제국 기도 수도 오지 아웃도어 브랜드 창업자 등반 루트 이름...
16,전쟁이 상수가 된다면,“전쟁에서 살아남고 싶다면 전쟁이 끝날 것이라는 환상부터 버려라.”\n2차 세계대전...,https://dbr.donga.com/article/view/1206/articl...,Editor’s Letter,440호 (2026년 5월 Issue 1),DBR,“전쟁에서 살아남고 싶다면 전쟁이 끝날 것이라는 환상부터 버려라.”\n2차 세계대전...,“전쟁에서 살아남고 싶다면 전쟁이 끝날 것이라는 환상부터 버려라.” 2차 세계대전을...,전쟁 전쟁 환상 세계 대전 승리 총리 회의실 소환 해협 유조선 긴장 항로 분쟁 상공...
17,"AI 시대, ‘똑똑하게 게으른 사람’들의 천국","AI로 기업 채용 현장이 빠르게 변하고 있다. 세일즈포스, 앤스로픽, 링크트인 같은...",https://dbr.donga.com/article/view/1801/articl...,DBR Column,440호 (2026년 5월 Issue 1),DBR,"AI로 기업 채용 현장이 빠르게 변하고 있다. 세일즈포스, 앤스로픽, 링크트인 같은...","AI로 기업 채용 현장이 빠르게 변하고 있다. 세일즈포스, 앤스로픽, 링크트인 같은...",AI 채용 현장 채용 과정 지원자 AI 결과물 핵심 평가 기준 AI 증강 성과 기준...
18,소비자의 온라인 칭찬 리뷰엔과한 감사보다 겸손 답글이 효과적,▶ Based on “Giving Thanks: How Managers Should...,https://dbr.donga.com/article/view/1202/articl...,Marketing,440호 (2026년 5월 Issue 1),DBR,▶ Based on “Giving Thanks: How Managers Should...,Based on “Giving Thanks: How Managers Should R...,Based on Giving Thanks How Managers Should Res...
19,"일상에 깊이 스며 있던 제품 단종 땐상실감 느낀 고객, 강한 반발할 수도",▶ Based on “Understanding customer grief in br...,https://dbr.donga.com/article/view/1202/articl...,Branding,440호 (2026년 5월 Issue 1),DBR,▶ Based on “Understanding customer grief in br...,Based on “Understanding customer grief in bran...,Based on Understanding customer grief in brand...

In [ ]:
!pip install keybert sentence-transformers -q

from keybert import KeyBERT
import pandas as pd

print("=" * 60)
print("[5단계] KeyBERT 키워드 추출")
print("=" * 60)


# ============================================================
# KeyBERT 키워드 추출
# ============================================================
# 사용 데이터프레임:
# - df_dbr_20
#
# 사용 컬럼:
# - analysis_content
#   → 노이즈 제거 + 명사 추출 + 불용어 제거가 완료된 분석용 텍스트
#
# 결과 컬럼:
# - keybert_keywords
#   → 기사별 추출 키워드 목록
#
# - keybert_keyword_scores
#   → 기사별 키워드와 유사도 점수 정보
# ============================================================


# KeyBERT 모델 초기화
# 한국어 텍스트에도 사용할 수 있는 다국어 문장 임베딩 모델 사용
kw_model = KeyBERT(model="paraphrase-multilingual-MiniLM-L12-v2")


def extract_keybert_keywords(text):
    # 값이 비어 있거나 NaN인 경우 빈 리스트 반환
    if pd.isna(text):
        return []

    text = str(text).strip()

    # 전처리 결과가 비어 있는 경우 빈 리스트 반환
    if text == "":
        return []

    # KeyBERT 키워드 추출
    keywords = kw_model.extract_keywords(
        text,
        keyphrase_ngram_range=(1, 1),  # 1개 단어로 구성된 키워드만 추출
        stop_words=None,               # 불용어는 이미 analysis_content에서 제거했으므로 None
        top_n=10                       # 기사 1개당 상위 10개 키워드 추출
    )

    return keywords


# analysis_content 컬럼을 기준으로 KeyBERT 키워드 추출
df_dbr_20["keybert_keyword_scores"] = df_dbr_20["analysis_content"].apply(
    extract_keybert_keywords
)

# 키워드만 따로 리스트 형태로 저장
df_dbr_20["keybert_keywords"] = df_dbr_20["keybert_keyword_scores"].apply(
    lambda keywords: [keyword for keyword, score in keywords]
)

print("-" * 60)
print("[KeyBERT 키워드 추출 결과 확인]")
print("-" * 60)

# 결과 확인
df_dbr_20[
    [
        "content",
        "clean_content",
        "analysis_content",
        "keybert_keywords",
        "keybert_keyword_scores"
    ]
].head()

============================================================
[5단계] KeyBERT 키워드 추출
============================================================

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

------------------------------------------------------------
[KeyBERT 키워드 추출 결과 확인]
------------------------------------------------------------

,content,clean_content,analysis_content,keybert_keywords,keybert_keyword_scores
0,아마존 설립자 제프 베이조스는 오래전부터 SF(과학소설) 팬이었습니다. 아마존이 2...,아마존 설립자 제프 베이조스는 오래전부터 SF 팬이었습니다. 아마존이 2010년대 ...,설립자 오래전 SF 개발 시작 당시 엔지니어 목표 스타트 컴퓨터 함장 컴퓨터 거리 ...,"[분석가, 엔지니어, 대리인, 테크, 설립자, 기관, 산업, 기계, 에이전트, 컴퓨터]","[(분석가, 0.454), (엔지니어, 0.4513), (대리인, 0.4483), ..."
1,“AI를 HR(인사·조직 관리)에 어디까지 써야 할까요?”\n최근 기업 경영진을 만...,“AI를 HR 에 어디까지 써야 할까요?” 최근 기업 경영진을 만나면 빠지지 않고 ...,AI HR 등장 함정 자체 AI 기술 범위 문제 축소 AI 적극 실험 글로벌 기술 ...,"[책임, 역할, 리더십, 규정, 책임자, 의무, 관리, 규제, ai, 이력서]","[(책임, 0.4675), (역할, 0.463), (리더십, 0.4526), (규정..."
2,▶ Based on “Who Avoids Punishment? How Discret...,Based on “Who Avoids Punishment? How Discretio...,Based on Who Avoids Punishment How Discretion ...,"[misconduct, 사이코패스, 처벌, punishment, 성격, psycho...","[(misconduct, 0.5546), (사이코패스, 0.5024), (처벌, 0..."
3,▶ Based on “Can Marketing Enable Firms to Coun...,Based on “Can Marketing Enable Firms to Counte...,Based on Can Marketing Enable Firms to Counter...,"[틈새시장, 시장, 마케팅, marketing, china, 경쟁, 산업, comp...","[(틈새시장, 0.5299), (시장, 0.4907), (마케팅, 0.482), (..."
4,▶ Based on “The Beauty Bias and Leader Emergen...,Based on “The Beauty Bias and Leader Emergence...,Based on The Beauty Bias and Leader Emergence ...,"[beauty, 매력, 견해, 개인주의, bias, 편견, emergence, 영향...","[(beauty, 0.498), (매력, 0.4518), (견해, 0.4024), ..."